using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class cond_grp_sel_def
    {
        public int cond_grp_sel_seq { get; set; }
        public int obj_num { get; set; }
        public string name { get; set; }
        public string ob_cond_grp_01_sel { get; set; }
        public string ob_cond_grp_02_sel { get; set; }
        public string ob_cond_grp_03_sel { get; set; }
        public string ob_cond_grp_04_sel { get; set; }
        public string ob_cond_grp_05_sel { get; set; }
        public string ob_cond_grp_06_sel { get; set; }
        public string ob_cond_grp_07_sel { get; set; }
        public string ob_cond_grp_08_sel { get; set; }
        public string ob_cond_grp_09_sel { get; set; }
        public string ob_cond_grp_10_sel { get; set; }
        public string ob_cond_grp_11_sel { get; set; }
        public string ob_cond_grp_12_sel { get; set; }
        public string ob_cond_grp_13_sel { get; set; }
        public string ob_cond_grp_14_sel { get; set; }
        public string ob_cond_grp_15_sel { get; set; }
        public string ob_cond_grp_16_sel { get; set; }
        public string ob_cond_grp_17_sel { get; set; }
        public string ob_cond_grp_18_sel { get; set; }
        public string ob_cond_grp_19_sel { get; set; }
        public string ob_cond_grp_20_sel { get; set; }
        public string ob_cond_grp_21_sel { get; set; }
        public string ob_cond_grp_22_sel { get; set; }
        public string ob_cond_grp_23_sel { get; set; }
        public string ob_cond_grp_24_sel { get; set; }
        public string ob_cond_grp_25_sel { get; set; }
        public string ob_cond_grp_26_sel { get; set; }
        public string ob_cond_grp_27_sel { get; set; }
        public string ob_cond_grp_28_sel { get; set; }
        public string ob_cond_grp_29_sel { get; set; }
        public string ob_cond_grp_30_sel { get; set; }
        public string ob_cond_grp_31_sel { get; set; }
        public string ob_cond_grp_32_sel { get; set; }
        public string ob_cond_grp_33_sel { get; set; }
        public string ob_cond_grp_34_sel { get; set; }
        public string ob_cond_grp_35_sel { get; set; }
        public string ob_cond_grp_36_sel { get; set; }
        public string ob_cond_grp_37_sel { get; set; }
        public string ob_cond_grp_38_sel { get; set; }
        public string ob_cond_grp_39_sel { get; set; }
        public string ob_cond_grp_40_sel { get; set; }
        public string ob_cond_grp_41_sel { get; set; }
        public string ob_cond_grp_42_sel { get; set; }
        public string ob_cond_grp_43_sel { get; set; }
        public string ob_cond_grp_44_sel { get; set; }
        public string ob_cond_grp_45_sel { get; set; }
        public string ob_cond_grp_46_sel { get; set; }
        public string ob_cond_grp_47_sel { get; set; }
        public string ob_cond_grp_48_sel { get; set; }
        public string ob_cond_grp_49_sel { get; set; }
        public string ob_cond_grp_50_sel { get; set; }
        public string ob_cond_grp_51_sel { get; set; }
        public string ob_cond_grp_52_sel { get; set; }
        public string ob_cond_grp_53_sel { get; set; }
        public string ob_cond_grp_54_sel { get; set; }
        public string ob_cond_grp_55_sel { get; set; }
        public string ob_cond_grp_56_sel { get; set; }
        public string ob_cond_grp_57_sel { get; set; }
        public string ob_cond_grp_58_sel { get; set; }
        public string ob_cond_grp_59_sel { get; set; }
        public string ob_cond_grp_60_sel { get; set; }
        public string ob_cond_grp_61_sel { get; set; }
        public string ob_cond_grp_62_sel { get; set; }
        public string ob_cond_grp_63_sel { get; set; }
        public string ob_cond_grp_64_sel { get; set; }
        public string ob_rsvd01 { get; set; }
        public string ob_rsvd02 { get; set; }
        public string ob_rsvd03 { get; set; }
        public string ob_rsvd04 { get; set; }
        public string ob_rsvd05 { get; set; }
        public string ob_rsvd06 { get; set; }
        public string ob_rsvd07 { get; set; }
        public string ob_rsvd08 { get; set; }
        public int? last_updated_by { get; set; }
        public DateTime? last_updated_date { get; set; }
        public string ob_cond_grp_65_sel { get; set; }
        public string ob_cond_grp_66_sel { get; set; }
        public string ob_cond_grp_67_sel { get; set; }
        public string ob_cond_grp_68_sel { get; set; }
        public string ob_cond_grp_69_sel { get; set; }
        public string ob_cond_grp_70_sel { get; set; }
        public string ob_cond_grp_71_sel { get; set; }
        public string ob_cond_grp_72_sel { get; set; }
        public string ob_cond_grp_73_sel { get; set; }
        public string ob_cond_grp_74_sel { get; set; }
        public string ob_cond_grp_75_sel { get; set; }
        public string ob_cond_grp_76_sel { get; set; }
        public string ob_cond_grp_77_sel { get; set; }
        public string ob_cond_grp_78_sel { get; set; }
        public string ob_cond_grp_79_sel { get; set; }
        public string ob_cond_grp_80_sel { get; set; }
        public string ob_cond_grp_81_sel { get; set; }
        public string ob_cond_grp_82_sel { get; set; }
        public string ob_cond_grp_83_sel { get; set; }
        public string ob_cond_grp_84_sel { get; set; }
        public string ob_cond_grp_85_sel { get; set; }
        public string ob_cond_grp_86_sel { get; set; }
        public string ob_cond_grp_87_sel { get; set; }
        public string ob_cond_grp_88_sel { get; set; }
        public string ob_cond_grp_89_sel { get; set; }
        public string ob_cond_grp_90_sel { get; set; }
        public string ob_cond_grp_91_sel { get; set; }
        public string ob_cond_grp_92_sel { get; set; }
        public string ob_cond_grp_93_sel { get; set; }
        public string ob_cond_grp_94_sel { get; set; }
        public string ob_cond_grp_95_sel { get; set; }
        public string ob_cond_grp_96_sel { get; set; }
        public string ob_cond_grp_97_sel { get; set; }
        public string ob_cond_grp_98_sel { get; set; }
        public string ob_cond_grp_99_sel { get; set; }
        public string ob_cond_grp_100_sel { get; set; }
        public string ob_cond_grp_101_sel { get; set; }
        public string ob_cond_grp_102_sel { get; set; }
        public string ob_cond_grp_103_sel { get; set; }
        public string ob_cond_grp_104_sel { get; set; }
        public string ob_cond_grp_105_sel { get; set; }
        public string ob_cond_grp_106_sel { get; set; }
        public string ob_cond_grp_107_sel { get; set; }
        public string ob_cond_grp_108_sel { get; set; }
        public string ob_cond_grp_109_sel { get; set; }
        public string ob_cond_grp_110_sel { get; set; }
        public string ob_cond_grp_111_sel { get; set; }
        public string ob_cond_grp_112_sel { get; set; }
        public string ob_cond_grp_113_sel { get; set; }
        public string ob_cond_grp_114_sel { get; set; }
        public string ob_cond_grp_115_sel { get; set; }
        public string ob_cond_grp_116_sel { get; set; }
        public string ob_cond_grp_117_sel { get; set; }
        public string ob_cond_grp_118_sel { get; set; }
        public string ob_cond_grp_119_sel { get; set; }
        public string ob_cond_grp_120_sel { get; set; }
        public string ob_cond_grp_121_sel { get; set; }
        public string ob_cond_grp_122_sel { get; set; }
        public string ob_cond_grp_123_sel { get; set; }
        public string ob_cond_grp_124_sel { get; set; }
        public string ob_cond_grp_125_sel { get; set; }
        public string ob_cond_grp_126_sel { get; set; }
        public string ob_cond_grp_127_sel { get; set; }
        public string ob_cond_grp_128_sel { get; set; }
        public string ob_cond_grp_129_sel { get; set; }
        public string ob_cond_grp_130_sel { get; set; }
        public string ob_cond_grp_131_sel { get; set; }
        public string ob_cond_grp_132_sel { get; set; }
        public string ob_cond_grp_133_sel { get; set; }
        public string ob_cond_grp_134_sel { get; set; }
        public string ob_cond_grp_135_sel { get; set; }
        public string ob_cond_grp_136_sel { get; set; }
        public string ob_cond_grp_137_sel { get; set; }
        public string ob_cond_grp_138_sel { get; set; }
        public string ob_cond_grp_139_sel { get; set; }
        public string ob_cond_grp_140_sel { get; set; }
        public string ob_cond_grp_141_sel { get; set; }
        public string ob_cond_grp_142_sel { get; set; }
        public string ob_cond_grp_143_sel { get; set; }
        public string ob_cond_grp_144_sel { get; set; }
        public string ob_cond_grp_145_sel { get; set; }
        public string ob_cond_grp_146_sel { get; set; }
        public string ob_cond_grp_147_sel { get; set; }
        public string ob_cond_grp_148_sel { get; set; }
        public string ob_cond_grp_149_sel { get; set; }
        public string ob_cond_grp_150_sel { get; set; }
        public string ob_cond_grp_151_sel { get; set; }
        public string ob_cond_grp_152_sel { get; set; }
        public string ob_cond_grp_153_sel { get; set; }
        public string ob_cond_grp_154_sel { get; set; }
        public string ob_cond_grp_155_sel { get; set; }
        public string ob_cond_grp_156_sel { get; set; }
        public string ob_cond_grp_157_sel { get; set; }
        public string ob_cond_grp_158_sel { get; set; }
        public string ob_cond_grp_159_sel { get; set; }
        public string ob_cond_grp_160_sel { get; set; }
        public string ob_cond_grp_161_sel { get; set; }
        public string ob_cond_grp_162_sel { get; set; }
        public string ob_cond_grp_163_sel { get; set; }
        public string ob_cond_grp_164_sel { get; set; }
        public string ob_cond_grp_165_sel { get; set; }
        public string ob_cond_grp_166_sel { get; set; }
        public string ob_cond_grp_167_sel { get; set; }
        public string ob_cond_grp_168_sel { get; set; }
        public string ob_cond_grp_169_sel { get; set; }
        public string ob_cond_grp_170_sel { get; set; }
        public string ob_cond_grp_171_sel { get; set; }
        public string ob_cond_grp_172_sel { get; set; }
        public string ob_cond_grp_173_sel { get; set; }
        public string ob_cond_grp_174_sel { get; set; }
        public string ob_cond_grp_175_sel { get; set; }
        public string ob_cond_grp_176_sel { get; set; }
        public string ob_cond_grp_177_sel { get; set; }
        public string ob_cond_grp_178_sel { get; set; }
        public string ob_cond_grp_179_sel { get; set; }
        public string ob_cond_grp_180_sel { get; set; }
        public string ob_cond_grp_181_sel { get; set; }
        public string ob_cond_grp_182_sel { get; set; }
        public string ob_cond_grp_183_sel { get; set; }
        public string ob_cond_grp_184_sel { get; set; }
        public string ob_cond_grp_185_sel { get; set; }
        public string ob_cond_grp_186_sel { get; set; }
        public string ob_cond_grp_187_sel { get; set; }
        public string ob_cond_grp_188_sel { get; set; }
        public string ob_cond_grp_189_sel { get; set; }
        public string ob_cond_grp_190_sel { get; set; }
        public string ob_cond_grp_191_sel { get; set; }
        public string ob_cond_grp_192_sel { get; set; }
        public string ob_cond_grp_193_sel { get; set; }
        public string ob_cond_grp_194_sel { get; set; }
        public string ob_cond_grp_195_sel { get; set; }
        public string ob_cond_grp_196_sel { get; set; }
        public string ob_cond_grp_197_sel { get; set; }
        public string ob_cond_grp_198_sel { get; set; }
        public string ob_cond_grp_199_sel { get; set; }
        public string ob_cond_grp_200_sel { get; set; }
        public string ob_cond_grp_201_sel { get; set; }
        public string ob_cond_grp_202_sel { get; set; }
        public string ob_cond_grp_203_sel { get; set; }
        public string ob_cond_grp_204_sel { get; set; }
        public string ob_cond_grp_205_sel { get; set; }
        public string ob_cond_grp_206_sel { get; set; }
        public string ob_cond_grp_207_sel { get; set; }
        public string ob_cond_grp_208_sel { get; set; }
        public string ob_cond_grp_209_sel { get; set; }
        public string ob_cond_grp_210_sel { get; set; }
        public string ob_cond_grp_211_sel { get; set; }
        public string ob_cond_grp_212_sel { get; set; }
        public string ob_cond_grp_213_sel { get; set; }
        public string ob_cond_grp_214_sel { get; set; }
        public string ob_cond_grp_215_sel { get; set; }
        public string ob_cond_grp_216_sel { get; set; }
        public string ob_cond_grp_217_sel { get; set; }
        public string ob_cond_grp_218_sel { get; set; }
        public string ob_cond_grp_219_sel { get; set; }
        public string ob_cond_grp_220_sel { get; set; }
        public string ob_cond_grp_221_sel { get; set; }
        public string ob_cond_grp_222_sel { get; set; }
        public string ob_cond_grp_223_sel { get; set; }
        public string ob_cond_grp_224_sel { get; set; }
        public string ob_cond_grp_225_sel { get; set; }
        public string ob_cond_grp_226_sel { get; set; }
        public string ob_cond_grp_227_sel { get; set; }
        public string ob_cond_grp_228_sel { get; set; }
        public string ob_cond_grp_229_sel { get; set; }
        public string ob_cond_grp_230_sel { get; set; }
        public string ob_cond_grp_231_sel { get; set; }
        public string ob_cond_grp_232_sel { get; set; }
        public string ob_cond_grp_233_sel { get; set; }
        public string ob_cond_grp_234_sel { get; set; }
        public string ob_cond_grp_235_sel { get; set; }
        public string ob_cond_grp_236_sel { get; set; }
        public string ob_cond_grp_237_sel { get; set; }
        public string ob_cond_grp_238_sel { get; set; }
        public string ob_cond_grp_239_sel { get; set; }
        public string ob_cond_grp_240_sel { get; set; }
        public string ob_cond_grp_241_sel { get; set; }
        public string ob_cond_grp_242_sel { get; set; }
        public string ob_cond_grp_243_sel { get; set; }
        public string ob_cond_grp_244_sel { get; set; }
        public string ob_cond_grp_245_sel { get; set; }
        public string ob_cond_grp_246_sel { get; set; }
        public string ob_cond_grp_247_sel { get; set; }
        public string ob_cond_grp_248_sel { get; set; }
        public string ob_cond_grp_249_sel { get; set; }
        public string ob_cond_grp_250_sel { get; set; }
        public string ob_cond_grp_251_sel { get; set; }
        public string ob_cond_grp_252_sel { get; set; }
        public string ob_cond_grp_253_sel { get; set; }
        public string ob_cond_grp_254_sel { get; set; }
        public string ob_cond_grp_255_sel { get; set; }
        public string ob_cond_grp_256_sel { get; set; }
    }
}
