using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class cond_grp_mem_def
    {
        public int cond_grp_mem_seq { get; set; }
        public int obj_num { get; set; }
        public string name { get; set; }
        public string ob_cond_grp_01_mem { get; set; }
        public string ob_cond_grp_02_mem { get; set; }
        public string ob_cond_grp_03_mem { get; set; }
        public string ob_cond_grp_04_mem { get; set; }
        public string ob_cond_grp_05_mem { get; set; }
        public string ob_cond_grp_06_mem { get; set; }
        public string ob_cond_grp_07_mem { get; set; }
        public string ob_cond_grp_08_mem { get; set; }
        public string ob_cond_grp_09_mem { get; set; }
        public string ob_cond_grp_10_mem { get; set; }
        public string ob_cond_grp_11_mem { get; set; }
        public string ob_cond_grp_12_mem { get; set; }
        public string ob_cond_grp_13_mem { get; set; }
        public string ob_cond_grp_14_mem { get; set; }
        public string ob_cond_grp_15_mem { get; set; }
        public string ob_cond_grp_16_mem { get; set; }
        public string ob_cond_grp_17_mem { get; set; }
        public string ob_cond_grp_18_mem { get; set; }
        public string ob_cond_grp_19_mem { get; set; }
        public string ob_cond_grp_20_mem { get; set; }
        public string ob_cond_grp_21_mem { get; set; }
        public string ob_cond_grp_22_mem { get; set; }
        public string ob_cond_grp_23_mem { get; set; }
        public string ob_cond_grp_24_mem { get; set; }
        public string ob_cond_grp_25_mem { get; set; }
        public string ob_cond_grp_26_mem { get; set; }
        public string ob_cond_grp_27_mem { get; set; }
        public string ob_cond_grp_28_mem { get; set; }
        public string ob_cond_grp_29_mem { get; set; }
        public string ob_cond_grp_30_mem { get; set; }
        public string ob_cond_grp_31_mem { get; set; }
        public string ob_cond_grp_32_mem { get; set; }
        public string ob_cond_grp_33_mem { get; set; }
        public string ob_cond_grp_34_mem { get; set; }
        public string ob_cond_grp_35_mem { get; set; }
        public string ob_cond_grp_36_mem { get; set; }
        public string ob_cond_grp_37_mem { get; set; }
        public string ob_cond_grp_38_mem { get; set; }
        public string ob_cond_grp_39_mem { get; set; }
        public string ob_cond_grp_40_mem { get; set; }
        public string ob_cond_grp_41_mem { get; set; }
        public string ob_cond_grp_42_mem { get; set; }
        public string ob_cond_grp_43_mem { get; set; }
        public string ob_cond_grp_44_mem { get; set; }
        public string ob_cond_grp_45_mem { get; set; }
        public string ob_cond_grp_46_mem { get; set; }
        public string ob_cond_grp_47_mem { get; set; }
        public string ob_cond_grp_48_mem { get; set; }
        public string ob_cond_grp_49_mem { get; set; }
        public string ob_cond_grp_50_mem { get; set; }
        public string ob_cond_grp_51_mem { get; set; }
        public string ob_cond_grp_52_mem { get; set; }
        public string ob_cond_grp_53_mem { get; set; }
        public string ob_cond_grp_54_mem { get; set; }
        public string ob_cond_grp_55_mem { get; set; }
        public string ob_cond_grp_56_mem { get; set; }
        public string ob_cond_grp_57_mem { get; set; }
        public string ob_cond_grp_58_mem { get; set; }
        public string ob_cond_grp_59_mem { get; set; }
        public string ob_cond_grp_60_mem { get; set; }
        public string ob_cond_grp_61_mem { get; set; }
        public string ob_cond_grp_62_mem { get; set; }
        public string ob_cond_grp_63_mem { get; set; }
        public string ob_cond_grp_64_mem { get; set; }
        public string ob_rsvd01 { get; set; }
        public string ob_rsvd02 { get; set; }
        public string ob_rsvd03 { get; set; }
        public string ob_rsvd04 { get; set; }
        public string ob_rsvd05 { get; set; }
        public string ob_rsvd06 { get; set; }
        public string ob_rsvd07 { get; set; }
        public string ob_rsvd08 { get; set; }
        public int? last_updated_by { get; set; }
        public DateTime? last_updated_date { get; set; }
        public string ob_cond_grp_65_mem { get; set; }
        public string ob_cond_grp_66_mem { get; set; }
        public string ob_cond_grp_67_mem { get; set; }
        public string ob_cond_grp_68_mem { get; set; }
        public string ob_cond_grp_69_mem { get; set; }
        public string ob_cond_grp_70_mem { get; set; }
        public string ob_cond_grp_71_mem { get; set; }
        public string ob_cond_grp_72_mem { get; set; }
        public string ob_cond_grp_73_mem { get; set; }
        public string ob_cond_grp_74_mem { get; set; }
        public string ob_cond_grp_75_mem { get; set; }
        public string ob_cond_grp_76_mem { get; set; }
        public string ob_cond_grp_77_mem { get; set; }
        public string ob_cond_grp_78_mem { get; set; }
        public string ob_cond_grp_79_mem { get; set; }
        public string ob_cond_grp_80_mem { get; set; }
        public string ob_cond_grp_81_mem { get; set; }
        public string ob_cond_grp_82_mem { get; set; }
        public string ob_cond_grp_83_mem { get; set; }
        public string ob_cond_grp_84_mem { get; set; }
        public string ob_cond_grp_85_mem { get; set; }
        public string ob_cond_grp_86_mem { get; set; }
        public string ob_cond_grp_87_mem { get; set; }
        public string ob_cond_grp_88_mem { get; set; }
        public string ob_cond_grp_89_mem { get; set; }
        public string ob_cond_grp_90_mem { get; set; }
        public string ob_cond_grp_91_mem { get; set; }
        public string ob_cond_grp_92_mem { get; set; }
        public string ob_cond_grp_93_mem { get; set; }
        public string ob_cond_grp_94_mem { get; set; }
        public string ob_cond_grp_95_mem { get; set; }
        public string ob_cond_grp_96_mem { get; set; }
        public string ob_cond_grp_97_mem { get; set; }
        public string ob_cond_grp_98_mem { get; set; }
        public string ob_cond_grp_99_mem { get; set; }
        public string ob_cond_grp_100_mem { get; set; }
        public string ob_cond_grp_101_mem { get; set; }
        public string ob_cond_grp_102_mem { get; set; }
        public string ob_cond_grp_103_mem { get; set; }
        public string ob_cond_grp_104_mem { get; set; }
        public string ob_cond_grp_105_mem { get; set; }
        public string ob_cond_grp_106_mem { get; set; }
        public string ob_cond_grp_107_mem { get; set; }
        public string ob_cond_grp_108_mem { get; set; }
        public string ob_cond_grp_109_mem { get; set; }
        public string ob_cond_grp_110_mem { get; set; }
        public string ob_cond_grp_111_mem { get; set; }
        public string ob_cond_grp_112_mem { get; set; }
        public string ob_cond_grp_113_mem { get; set; }
        public string ob_cond_grp_114_mem { get; set; }
        public string ob_cond_grp_115_mem { get; set; }
        public string ob_cond_grp_116_mem { get; set; }
        public string ob_cond_grp_117_mem { get; set; }
        public string ob_cond_grp_118_mem { get; set; }
        public string ob_cond_grp_119_mem { get; set; }
        public string ob_cond_grp_120_mem { get; set; }
        public string ob_cond_grp_121_mem { get; set; }
        public string ob_cond_grp_122_mem { get; set; }
        public string ob_cond_grp_123_mem { get; set; }
        public string ob_cond_grp_124_mem { get; set; }
        public string ob_cond_grp_125_mem { get; set; }
        public string ob_cond_grp_126_mem { get; set; }
        public string ob_cond_grp_127_mem { get; set; }
        public string ob_cond_grp_128_mem { get; set; }
        public string ob_cond_grp_129_mem { get; set; }
        public string ob_cond_grp_130_mem { get; set; }
        public string ob_cond_grp_131_mem { get; set; }
        public string ob_cond_grp_132_mem { get; set; }
        public string ob_cond_grp_133_mem { get; set; }
        public string ob_cond_grp_134_mem { get; set; }
        public string ob_cond_grp_135_mem { get; set; }
        public string ob_cond_grp_136_mem { get; set; }
        public string ob_cond_grp_137_mem { get; set; }
        public string ob_cond_grp_138_mem { get; set; }
        public string ob_cond_grp_139_mem { get; set; }
        public string ob_cond_grp_140_mem { get; set; }
        public string ob_cond_grp_141_mem { get; set; }
        public string ob_cond_grp_142_mem { get; set; }
        public string ob_cond_grp_143_mem { get; set; }
        public string ob_cond_grp_144_mem { get; set; }
        public string ob_cond_grp_145_mem { get; set; }
        public string ob_cond_grp_146_mem { get; set; }
        public string ob_cond_grp_147_mem { get; set; }
        public string ob_cond_grp_148_mem { get; set; }
        public string ob_cond_grp_149_mem { get; set; }
        public string ob_cond_grp_150_mem { get; set; }
        public string ob_cond_grp_151_mem { get; set; }
        public string ob_cond_grp_152_mem { get; set; }
        public string ob_cond_grp_153_mem { get; set; }
        public string ob_cond_grp_154_mem { get; set; }
        public string ob_cond_grp_155_mem { get; set; }
        public string ob_cond_grp_156_mem { get; set; }
        public string ob_cond_grp_157_mem { get; set; }
        public string ob_cond_grp_158_mem { get; set; }
        public string ob_cond_grp_159_mem { get; set; }
        public string ob_cond_grp_160_mem { get; set; }
        public string ob_cond_grp_161_mem { get; set; }
        public string ob_cond_grp_162_mem { get; set; }
        public string ob_cond_grp_163_mem { get; set; }
        public string ob_cond_grp_164_mem { get; set; }
        public string ob_cond_grp_165_mem { get; set; }
        public string ob_cond_grp_166_mem { get; set; }
        public string ob_cond_grp_167_mem { get; set; }
        public string ob_cond_grp_168_mem { get; set; }
        public string ob_cond_grp_169_mem { get; set; }
        public string ob_cond_grp_170_mem { get; set; }
        public string ob_cond_grp_171_mem { get; set; }
        public string ob_cond_grp_172_mem { get; set; }
        public string ob_cond_grp_173_mem { get; set; }
        public string ob_cond_grp_174_mem { get; set; }
        public string ob_cond_grp_175_mem { get; set; }
        public string ob_cond_grp_176_mem { get; set; }
        public string ob_cond_grp_177_mem { get; set; }
        public string ob_cond_grp_178_mem { get; set; }
        public string ob_cond_grp_179_mem { get; set; }
        public string ob_cond_grp_180_mem { get; set; }
        public string ob_cond_grp_181_mem { get; set; }
        public string ob_cond_grp_182_mem { get; set; }
        public string ob_cond_grp_183_mem { get; set; }
        public string ob_cond_grp_184_mem { get; set; }
        public string ob_cond_grp_185_mem { get; set; }
        public string ob_cond_grp_186_mem { get; set; }
        public string ob_cond_grp_187_mem { get; set; }
        public string ob_cond_grp_188_mem { get; set; }
        public string ob_cond_grp_189_mem { get; set; }
        public string ob_cond_grp_190_mem { get; set; }
        public string ob_cond_grp_191_mem { get; set; }
        public string ob_cond_grp_192_mem { get; set; }
        public string ob_cond_grp_193_mem { get; set; }
        public string ob_cond_grp_194_mem { get; set; }
        public string ob_cond_grp_195_mem { get; set; }
        public string ob_cond_grp_196_mem { get; set; }
        public string ob_cond_grp_197_mem { get; set; }
        public string ob_cond_grp_198_mem { get; set; }
        public string ob_cond_grp_199_mem { get; set; }
        public string ob_cond_grp_200_mem { get; set; }
        public string ob_cond_grp_201_mem { get; set; }
        public string ob_cond_grp_202_mem { get; set; }
        public string ob_cond_grp_203_mem { get; set; }
        public string ob_cond_grp_204_mem { get; set; }
        public string ob_cond_grp_205_mem { get; set; }
        public string ob_cond_grp_206_mem { get; set; }
        public string ob_cond_grp_207_mem { get; set; }
        public string ob_cond_grp_208_mem { get; set; }
        public string ob_cond_grp_209_mem { get; set; }
        public string ob_cond_grp_210_mem { get; set; }
        public string ob_cond_grp_211_mem { get; set; }
        public string ob_cond_grp_212_mem { get; set; }
        public string ob_cond_grp_213_mem { get; set; }
        public string ob_cond_grp_214_mem { get; set; }
        public string ob_cond_grp_215_mem { get; set; }
        public string ob_cond_grp_216_mem { get; set; }
        public string ob_cond_grp_217_mem { get; set; }
        public string ob_cond_grp_218_mem { get; set; }
        public string ob_cond_grp_219_mem { get; set; }
        public string ob_cond_grp_220_mem { get; set; }
        public string ob_cond_grp_221_mem { get; set; }
        public string ob_cond_grp_222_mem { get; set; }
        public string ob_cond_grp_223_mem { get; set; }
        public string ob_cond_grp_224_mem { get; set; }
        public string ob_cond_grp_225_mem { get; set; }
        public string ob_cond_grp_226_mem { get; set; }
        public string ob_cond_grp_227_mem { get; set; }
        public string ob_cond_grp_228_mem { get; set; }
        public string ob_cond_grp_229_mem { get; set; }
        public string ob_cond_grp_230_mem { get; set; }
        public string ob_cond_grp_231_mem { get; set; }
        public string ob_cond_grp_232_mem { get; set; }
        public string ob_cond_grp_233_mem { get; set; }
        public string ob_cond_grp_234_mem { get; set; }
        public string ob_cond_grp_235_mem { get; set; }
        public string ob_cond_grp_236_mem { get; set; }
        public string ob_cond_grp_237_mem { get; set; }
        public string ob_cond_grp_238_mem { get; set; }
        public string ob_cond_grp_239_mem { get; set; }
        public string ob_cond_grp_240_mem { get; set; }
        public string ob_cond_grp_241_mem { get; set; }
        public string ob_cond_grp_242_mem { get; set; }
        public string ob_cond_grp_243_mem { get; set; }
        public string ob_cond_grp_244_mem { get; set; }
        public string ob_cond_grp_245_mem { get; set; }
        public string ob_cond_grp_246_mem { get; set; }
        public string ob_cond_grp_247_mem { get; set; }
        public string ob_cond_grp_248_mem { get; set; }
        public string ob_cond_grp_249_mem { get; set; }
        public string ob_cond_grp_250_mem { get; set; }
        public string ob_cond_grp_251_mem { get; set; }
        public string ob_cond_grp_252_mem { get; set; }
        public string ob_cond_grp_253_mem { get; set; }
        public string ob_cond_grp_254_mem { get; set; }
        public string ob_cond_grp_255_mem { get; set; }
        public string ob_cond_grp_256_mem { get; set; }
        public string ob_allow_substitute { get; set; }
    }
}
