using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class emp_class_def
    {
        public int emp_class_seq { get; set; }
        public int obj_num { get; set; }
        public string name { get; set; }
        public int? default_ts_scrn { get; set; }
        public short proc_priv_lvl { get; set; }
        public short su_proc_priv_lvl { get; set; }
        public short aseq_priv_lvl { get; set; }
        public short mi_priv_lvl { get; set; }
        public short dsc_priv_lvl { get; set; }
        public short svc_priv_lvl { get; set; }
        public short tmed_priv_lvl { get; set; }
        public short auth_clk_in_priv_lvl { get; set; }
        public short clk_in_priv_lvl { get; set; }
        public string ob_et01_tbl_entry_req { get; set; }
        public string ob_et02_cov_entry_req { get; set; }
        public string ob_et03_chk_pickup_req { get; set; }
        public string ob_et04_prompt_for_chk_emp { get; set; }
        public string ob_et05_prn_on_demand { get; set; }
        public string ob_et06_prn_special_by_rnd { get; set; }
        public string ob_et07_prn_ln_by_ln_rcpt { get; set; }
        public string ob_et08_sign_out_after_trans { get; set; }
        public string ob_et13_bank_entry_req { get; set; }
        public string ob_et14_seat_entry_req { get; set; }
        public string ob_et16_lds_fast_trans { get; set; }
        public string ob_et17_chk_id_entry_req { get; set; }
        public string ob_et18_use_preset_sign_in { get; set; }
        public string ob_et19_req_mag_card_id { get; set; }
        public string ob_et_limit_last_item_void { get; set; }
        public string ob_et_incr_shift_clock_in { get; set; }
        public string ob_et_no_emp_rvc_change { get; set; }
        public string ob_tbl_assign { get; set; }
        public string ob_dd_driver { get; set; }
        public string ob_sec_auth_reqd { get; set; }
        public string ob_et_rsvd04 { get; set; }
        public string ob_et_rsvd05 { get; set; }
        public string ob_et_rsvd06 { get; set; }
        public string ob_et_rsvd07 { get; set; }
        public string ob_et_rsvd08 { get; set; }
        public string ob_et_rsvd09 { get; set; }
        public string ob_et_rsvd10 { get; set; }
        public string ob_tpriv04_clk_in_outside_gr { get; set; }
        public string ob_tpriv05_sign_in { get; set; }
        public string ob_tpriv06_assign_cshr { get; set; }
        public string ob_tpriv07_change_cshr { get; set; }
        public string ob_tpriv08_assign_drwr { get; set; }
        public string ob_tpriv09_begin_chk { get; set; }
        public string ob_tpriv10_pickup_opn_on_sys { get; set; }
        public string ob_tpriv11_pickup_others_chk { get; set; }
        public string ob_tpriv12_mi_others_chk { get; set; }
        public string ob_tpriv13_dsc_others_chk { get; set; }
        public string ob_tpriv14_svc_others_chk { get; set; }
        public string ob_tpriv15_tmed_others_chk { get; set; }
        public string ob_tpriv16_reprn_tm_card { get; set; }
        public string ob_tpriv17_reprn_chk { get; set; }
        public string ob_tpriv18_change_main_mlvl { get; set; }
        public string ob_tpriv19_change_sub_mlvl { get; set; }
        public string ob_tpriv20_change_kybd { get; set; }
        public string ob_tpriv21_tmed_over_halo { get; set; }
        public string ob_tpriv22_xfer_chk { get; set; }
        public string ob_tpriv23_add_chk { get; set; }
        public string ob_tpriv24_edit_cchk { get; set; }
        public string ob_tpriv25_void_prev_rnd_mi { get; set; }
        public string ob_tpriv26_vd_rtn_non_chk_mi { get; set; }
        public string ob_tpriv27_void_prev_rnd_dsc { get; set; }
        public string ob_tpriv28_void_prev_rnd_svc { get; set; }
        public string ob_tpriv29_void_prv_rnd_tmed { get; set; }
        public string ob_tpriv30_current_rnd_void { get; set; }
        public string ob_tpriv31_drive_trans_neg { get; set; }
        public string ob_tpriv32_rtn_mi { get; set; }
        public string ob_tpriv33_tax_exempt { get; set; }
        public string ob_tpriv34_exempt_auto_svc { get; set; }
        public string ob_tpriv35_change_cov { get; set; }
        public string ob_tpriv36_do_trans_cancel { get; set; }
        public string ob_tpriv37_no_sale { get; set; }
        public string ob_tpriv38_decl_tip { get; set; }
        public string ob_tpriv39_change_order_type { get; set; }
        public string ob_tpriv40_item_weight { get; set; }
        public string ob_tpriv53_clk_out_open_chk { get; set; }
        public string ob_tpriv54_post_tmed { get; set; }
        public string ob_tpriv55_pay_zero_bal { get; set; }
        public string ob_tpriv56_pay_neg_bal { get; set; }
        public string ob_tpriv57_use_tbl_key { get; set; }
        public string ob_tpriv58_prn_memo_chk { get; set; }
        public string ob_tpriv59_reprn_memo_chk { get; set; }
        public string ob_tpriv60_split_chk { get; set; }
        public string ob_tpriv61_void_trans { get; set; }
        public string ob_tpriv62_block_trans_chk { get; set; }
        public string ob_tpriv63_ignore_lds_optr { get; set; }
        public string ob_tpriv64_change_lds_rvc { get; set; }
        public string ob_tpriv65_reprn_cc_vchr { get; set; }
        public string ob_tpriv66_manual_cc_auth { get; set; }
        public string ob_tpriv67_prn_shared_chk { get; set; }
        public string ob_tpriv68_reprn_clsd_chk { get; set; }
        public string ob_tpriv69_edit_reconcld_chk { get; set; }
        public string ob_tpriv70_auth_trans_cancel { get; set; }
        public string ob_tpriv71_manl_cc_inf_entr { get; set; }
        public string ob_tpriv72_edit_chk_id { get; set; }
        public string ob_tpriv73_edit_clsd_chk_id { get; set; }
        public string ob_tpriv74_overide_clk_grace { get; set; }
        public string ob_tpriv75_sim_priv_1 { get; set; }
        public string ob_tpriv76_sim_priv_2 { get; set; }
        public string ob_tpriv77_sim_priv_3 { get; set; }
        public string ob_tpriv78_sim_priv_4 { get; set; }
        public string ob_tpriv79_chng_sign_in_asgn { get; set; }
        public string ob_tpriv_share_item { get; set; }
        public string ob_tpriv_begin_clk_out_chk { get; set; }
        public string ob_tpriv_edit_prev_shift_chk { get; set; }
        public string ob_tpriv_change_uws_rvc { get; set; }
        public string ob_tpriv_use_price_ovrde { get; set; }
        public string ob_tpriv_pay_cancelled_ca { get; set; }
        public string ob_tpriv_run_all_sar_rpts { get; set; }
        public string ob_tpriv_run_emp_sar_rpts { get; set; }
        public string ob_tpriv_void_rnd_after_ca { get; set; }
        public string ob_tpriv_show_rcp_portion { get; set; }
        public string ob_tpriv_access_othr_emp_tbl { get; set; }
        public string ob_tpriv_enter_sar { get; set; }
        public string ob_tpriv_enter_bsm { get; set; }
        public string ob_tpriv_override_lock_out { get; set; }
        public string ob_tpriv_clk_in_unsched_job { get; set; }
        public string ob_tpriv_dd_add_xfer_others { get; set; }
        public string ob_tpriv_sign_in_locked_emp { get; set; }
        public string ob_tpriv_reopen_closed_check { get; set; }
        public string ob_tpriv_block_settlement { get; set; }
        public string ob_tpriv_void_reopen_mi { get; set; }
        public string ob_tpriv_void_reopen_dsc { get; set; }
        public string ob_tpriv_void_reopen_svc { get; set; }
        public string ob_tpriv_assign_driver { get; set; }
        public string ob_void_lds_item { get; set; }
        public string ob_tpriv_rsvd07 { get; set; }
        public string ob_tpriv_rsvd08 { get; set; }
        public string ob_tpriv_rsvd01 { get; set; }
        public string ob_tpriv_rsvd02 { get; set; }
        public string ob_tpriv_rsvd03 { get; set; }
        public string ob_tpriv_rsvd04 { get; set; }
        public string ob_spriv05_clear_all_totals { get; set; }
        public string ob_spriv06_use_mgr_proc { get; set; }
        public string ob_spriv09_emp_assign_proc { get; set; }
        public string ob_spriv10_emp_train_proc { get; set; }
        public string ob_spriv11_redir_ordr_dev { get; set; }
        public string ob_spriv12_mi_assign_proc { get; set; }
        public string ob_spriv13_mi_avail_proc { get; set; }
        public string ob_spriv17_adj_time_card { get; set; }
        public string ob_spriv18_set_cncy_rate { get; set; }
        public string ob_spriv19_use_sys_rpts { get; set; }
        public string ob_spriv34_media_dec_proc { get; set; }
        public string ob_spriv35_chng_media_dec { get; set; }
        public string ob_spriv_set_business_date { get; set; }
        public string ob_spriv_chng_emp_shift { get; set; }
        public string ob_spriv_chng_cshr_shift { get; set; }
        public string ob_spriv_create_cc_batch { get; set; }
        public string ob_spriv_edit_cc_batch { get; set; }
        public string ob_spriv_report_cc_batch { get; set; }
        public string ob_spriv_settle_cc_batch { get; set; }
        public string ob_spriv_use_forms_designer { get; set; }
        public string ob_spriv_allow_mp_add_delete { get; set; }
        public string ob_spriv_use_db_maintenance { get; set; }
        public string ob_spriv_use_em_configurator { get; set; }
        public string ob_spriv_limit_mi_mp_access { get; set; }
        public string ob_spriv_limit_emp_mp_acces { get; set; }
        public string ob_spriv_use_tbl_asgn { get; set; }
        public string ob_spriv_use_su_status { get; set; }
        public string ob_spriv_combo_meal_proc { get; set; }
        public string ob_spriv_srv_prd { get; set; }
        public string ob_spriv_srv_prd_other_rvc { get; set; }
        public string ob_spriv_rsvd09 { get; set; }
        public string ob_spriv_rsvd06 { get; set; }
        public string ob_spriv_rsvd07 { get; set; }
        public string ob_spriv_rsvd08 { get; set; }
        public string ob_spriv_use_ta { get; set; }
        public string ob_spriv_save_ta_config { get; set; }
        public string ob_spriv_delete_ta_config { get; set; }
        public string ob_su_spriv01_access_sys_cfg { get; set; }
        public string ob_su_spriv05_utilities_clear { get; set; }
        public string ob_su_spriv06_access_mgr_proc { get; set; }
        public string ob_su_spriv09_emp_asgn_proc { get; set; }
        public string ob_su_spriv10_emp_train_proc { get; set; }
        public string ob_su_spriv11_redir_ordr_dev { get; set; }
        public string ob_su_spriv12_mi_assign_proc { get; set; }
        public string ob_su_spriv13_mi_avail_proc { get; set; }
        public string ob_su_spriv14_chng_dev_status { get; set; }
        public string ob_su_spriv16_restore_gst_chk { get; set; }
        public string ob_su_spriv18_set_cncy_rate { get; set; }
        public string ob_su_spriv19_access_sys_rpts { get; set; }
        public string ob_su_spriv20_reset_rpt { get; set; }
        public string ob_su_spriv21_no_prn_rpts { get; set; }
        public string ob_su_spriv22_run_aseq { get; set; }
        public string ob_su_spriv25_run_mgr_rpts { get; set; }
        public string ob_su_spriv26_run_grp_1_rpts { get; set; }
        public string ob_su_spriv27_run_grp_2_rpts { get; set; }
        public string ob_su_spriv28_run_grp_3_rpts { get; set; }
        public string ob_su_spriv29_run_grp_4_rpts { get; set; }
        public string ob_su_spriv30_run_grp_5_rpts { get; set; }
        public string ob_su_spriv31_run_grp_6_rpts { get; set; }
        public string ob_su_spriv32_run_grp_7_rpts { get; set; }
        public string ob_su_spriv33_clear_lds { get; set; }
        public string ob_su_spriv34_media_dec_proc { get; set; }
        public string ob_su_spriv35_chng_media_dec { get; set; }
        public string ob_hide_mgr_proc_emp_id { get; set; }
        public string ob_hide_sys_cfg_emp_id { get; set; }
        public DateTime? last_updated_date { get; set; }
        public int? last_updated_by { get; set; }
        public string ob_tpriv_use_pm_waste { get; set; }
        public int? cond_grp_mask_01 { get; set; }
        public int? cond_grp_mask_02 { get; set; }
        public int? ob_flags { get; set; }
        public string ob_tpriv_rsvd05 { get; set; }
        public string ob_tpriv_rsvd06 { get; set; }
        public string ob_set_kitchen_theme { get; set; }
        public string ob_cm_till_reopen { get; set; }
        public string ob_cm_till_assign_to_uws { get; set; }
        public string ob_cm_till_assign_employee { get; set; }
        public string ob_cm_till_close { get; set; }
        public string ob_cm_till_count { get; set; }
        public string ob_cm_till_adjust_count { get; set; }
        public string ob_cm_till_view_variance { get; set; }
        public string ob_cm_till_transfer { get; set; }
        public string ob_cm_till_set_starting_amount { get; set; }
        public string ob_cm_till_cash_pull { get; set; }
        public string ob_cm_till_quick_start { get; set; }
        public string ob_cm_safe_open { get; set; }
        public string ob_cm_safe_close { get; set; }
        public string ob_cm_safe_count { get; set; }
        public string ob_cm_safe_paid_in { get; set; }
        public string ob_cm_safe_paid_out { get; set; }
        public string ob_cm_safe_transfer { get; set; }
        public string ob_cm_view_totals { get; set; }
        public string ob_cm_configuration { get; set; }
        public string ob_cm_deposit_open { get; set; }
        public string ob_cm_deposit_edit { get; set; }
        public string ob_cm_deposit_from_till { get; set; }
        public string ob_cm_deposit_from_safe { get; set; }
        public string ob_cm_deposit_close { get; set; }
        public string ob_cm_purge_detail { get; set; }
        public int? cm_accounting_method { get; set; }
        public int? hht_default_ts_scrn { get; set; }
        public string ob_auth_cond_pers_chk_approval { get; set; }
        public string ob_tpriv_override_discount { get; set; }
        public int? cond_grp_mask_03 { get; set; }
        public int? cond_grp_mask_04 { get; set; }
        public int? cond_grp_mask_05 { get; set; }
        public int? cond_grp_mask_06 { get; set; }
        public int? cond_grp_mask_07 { get; set; }
        public int? cond_grp_mask_08 { get; set; }
        public string ob_override_cc_masking { get; set; }
        public string ob_gss_back_office { get; set; }
        public string ob_gss_screen_design { get; set; }
        public string ob_gss_bns_crtfct_cpn_cfg { get; set; }
        public string ob_gss_bonus_points_adjust { get; set; }
        public string ob_gss_ar_configuration { get; set; }
        public string ob_gss_ar_posting { get; set; }
        public string ob_gss_export_import { get; set; }
        public string ob_gss_delivery_edit { get; set; }
        public string ob_gss_configuration { get; set; }
        public string ob_use_dashboard { get; set; }
        public string ob_view_dashboard_sales { get; set; }
        public string ob_view_dashboard_kitchen { get; set; }
        public string ob_view_dashboard_labor { get; set; }
        public string ob_view_dashboard_employee { get; set; }
        public string ob_view_dashboard_contest { get; set; }
        public string ob_edit_dashboard_contest { get; set; }
        public string ob_allow_prev_rnd_acr { get; set; }
        public string ob_tpriv80_appl_use_pw_id { get; set; }
        public string ob_team_member { get; set; }
        public string ob_gss_accept_invalid_street { get; set; }
        public string ob_pos_api_emp { get; set; }
        public string ob_allow_rebuild { get; set; }
        public string ob_allow_ekey_change { get; set; }
        public string ob_allow_backup { get; set; }
        public string ob_allow_restore { get; set; }
        public string ob_allow_secure_log { get; set; }
        public string ob_allow_trans_log { get; set; }
        public string ob_allow_new_user { get; set; }
        public string ob_override_charged_tip_limit { get; set; }
        public string ob_submit_blank_avs { get; set; }
        public string ob_submit_blank_cvv { get; set; }
        public string ob_auth_cond_approval { get; set; }
        public string ob_tpriv_void_closed_check { get; set; }
        public string ob_tms_add_waitlist_entry { get; set; }
        public string ob_tms_edit_waitlist_entry { get; set; }
        public string ob_tms_abandon_waitlist_entry { get; set; }
        public string ob_tms_seat_waitlist_entry { get; set; }
        public string ob_tms_assign_tbl_to_sect { get; set; }
        public string ob_tms_assign_emp_to_tbl { get; set; }
        public string ob_tms_assign_emp_to_sect { get; set; }
        public string ob_tms_clear_tbl_assignments { get; set; }
        public string ob_tms_set_tbl_clean_dirty { get; set; }
        public string ob_tms_set_tbl_state { get; set; }
        public string ob_tms_add_reservation_entry { get; set; }
        public string ob_tms_edit_reservation_entry { get; set; }
        public string ob_tms_cancel_reservation_entry { get; set; }
        public string ob_tms_approv_reservation_entry { get; set; }
        public string ob_tms_greet_tbl_request_entry { get; set; }
        public string ob_tms_unlock_tbl_request { get; set; }
        public string ob_tms_reinitialize { get; set; }
        public string ob_tms_invalid_seating_override { get; set; }
        public string ob_pickup_offline_sys_chk { get; set; }
        public string ob_allow_tbl_reassignment { get; set; }
        public string ob_tpriv_corrective_auth { get; set; }
        public string ob_tms_info_display { get; set; }
        public string ob_ignore_min_tips_requirement { get; set; }
        public string ob_cm_till_enhanced_quick_start { get; set; }
        public string ob_cm_allow_clk_out_w_open_till { get; set; }
        public string ob_tpriv_return_trans { get; set; }
        public short clk_in_auth_mode { get; set; }
        public short sign_in_auth_mode { get; set; }
        public short trans_auth_mode { get; set; }
        public short tm_clk_auth_mode { get; set; }
        public short pc_appl_auth_mode { get; set; }
        public string ob_cm_deposit_view_blind { get; set; }
        public string ob_allow_enroll_fp { get; set; }
        public string ob_override_cobranded_cc { get; set; }
        public string ob_launch_alert_viewer { get; set; }
        public int? operating_emp_class { get; set; }
        public string ob_auth_check_begin_before_till { get; set; }
        public string ob_allow_prev_round_com_itm_chg { get; set; }
        public string ob_allow_prev_round_cancel_ordr { get; set; }
        public string ob_allow_mp_add_price { get; set; }
        public string ob_order_type_promise_tm_adjust { get; set; }
        public string ob_chk_xfer_rqst_in { get; set; }
        public string ob_chk_xfer_rqst_out { get; set; }
        public string ob_pickup_future_order_chk { get; set; }
        public string ob_disable_forced_beverage { get; set; }
        public string ob_refund_edit_clsd_chk { get; set; }
        public string ob_cm_pc_open { get; set; }
        public string ob_cm_pc_close { get; set; }
        public string ob_cm_pc_count { get; set; }
        public string ob_cm_pc_paid_in { get; set; }
        public string ob_cm_pc_paid_out { get; set; }
        public string ob_cm_pc_transfer { get; set; }
        public string ob_cm_deposit_from_pc { get; set; }
        public string ob_minor_prev_round_com_change { get; set; }
        public string ob_dsc_after_srvc_ttl { get; set; }
        public string ob_cm_till_close_boh { get; set; }
        public string ob_cm_serverbank_close_boh { get; set; }
        public string ob_do_not_prompt_for_paid_break { get; set; }
        public string ob_do_not_prompt_for_unpaid_brk { get; set; }
        public string ob_clkin_after_recent_clkout { get; set; }
        public string ob_update_other_driver_avail { get; set; }
        public string ob_dd_skip_transfer_confirm { get; set; }
        public string ob_dd_skip_open_chk_confirm { get; set; }
        public string ob_exempt_incl_svc { get; set; }
        public string ob_tms_edit_sect_layout { get; set; }
        public string ob_tms_activate_sect_layout { get; set; }
        public string ob_tms_delete_sect_layout { get; set; }
        public string ob_et_prn_special_on_demand { get; set; }
        public string ob_tms_edit_server_effic_rating { get; set; }
        public string ob_include_in_server_list { get; set; }
        public string ob_tms_edit_server_availability { get; set; }
        public string ob_make_order_xfer { get; set; }
        public string ob_cm_free_reason { get; set; }
        public string ob_tpriv_reopen_clsd_chck_dscnt { get; set; }
        public string ob_associate_mStation { get; set; }
        public string ob_disassociate_mStation { get; set; }
        public string ob_zero_value_prev_round_change { get; set; }
        public string ob_tender_initial_auth { get; set; }
    }
}
