using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class emp_chg_dtl
    {
        public int emp_chg_seq { get; set; }
        public string trans_type { get; set; }
        public string reason_code { get; set; }
        public int? emp_seq { get; set; }
        public int? emp_bo_class_seq { get; set; }
        public int? cntry_seq { get; set; }
        public int? state_seq { get; set; }
        public int? bank_seq { get; set; }
        public int? bank_2_seq { get; set; }
        public int? obj_num { get; set; }
        public string payroll_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string long_last_name { get; set; }
        public string long_first_name { get; set; }
        public string middle_name { get; set; }
        public string suffix { get; set; }
        public string chk_name { get; set; }
        public string chk_name2 { get; set; }
        public string prev_last_name { get; set; }
        public decimal? id { get; set; }
        public decimal? pc_appl_id { get; set; }
        public int? lang_seq { get; set; }
        public int? emp_class_seq { get; set; }
        public string ob_et09_minor { get; set; }
        public string ob_et10_disp_cond_help { get; set; }
        public string ob_rsvd06 { get; set; }
        public string ob_rsvd02 { get; set; }
        public string ob_rsvd03 { get; set; }
        public string ob_rsvd04 { get; set; }
        public string ob_rsvd05 { get; set; }
        public short? late_clk_in_grace { get; set; }
        public short active_drwr { get; set; }
        public DateTime? effective_from { get; set; }
        public DateTime? effective_to { get; set; }
        public DateTime? date_of_birth { get; set; }
        public string ob_part_time { get; set; }
        public string ob_exempt { get; set; }
        public string ob_sched_ghost { get; set; }
        public string ob_salaried { get; set; }
        public short? lds_optr_num { get; set; }
        public int? su_trk_grp_seq { get; set; }
        public int? opt_su_trk_grp_seq { get; set; }
        public string addr_ln_1 { get; set; }
        public string addr_ln_2 { get; set; }
        public string city { get; set; }
        public string county { get; set; }
        public string postal_code { get; set; }
        public string ob_in_city_limits { get; set; }
        public int? school_district_seq { get; set; }
        public string prefix { get; set; }
        public string local_num_1 { get; set; }
        public string ext_1 { get; set; }
        public string fax_local_num { get; set; }
        public string other_local_num { get; set; }
        public string pager_local_num { get; set; }
        public string pager_ext { get; set; }
        public string ob_local_num_1_unlisted { get; set; }
        public string e_mail_addr { get; set; }
        public string emergency_name { get; set; }
        public string emergency_number { get; set; }
        public string emergency_addr { get; set; }
        public string contact_relation { get; set; }
        public string ssn { get; set; }
        public string ethnicity { get; set; }
        public string gender { get; set; }
        public DateTime? hire_date { get; set; }
        public string ob_re_hire { get; set; }
        public string fed_mar_status { get; set; }
        public short? fed_exemptions { get; set; }
        public decimal? fed_addtl { get; set; }
        public string ob_fed_tax_exempt { get; set; }
        public string state_mar_status { get; set; }
        public short? state_exemptions { get; set; }
        public decimal? state_addtl { get; set; }
        public string ob_state_tax_exempt { get; set; }
        public short? local_exemptions { get; set; }
        public decimal? county_addtl { get; set; }
        public string ob_county_tax_exempt { get; set; }
        public decimal? city_addtl { get; set; }
        public string ob_city_tax_exempt { get; set; }
        public string i9_id_cat { get; set; }
        public string i9_id1_type { get; set; }
        public string i9_id1_number { get; set; }
        public DateTime? i9_id1_expiration { get; set; }
        public string i9_id2_type { get; set; }
        public string i9_id2_number { get; set; }
        public DateTime? i9_id2_expiration { get; set; }
        public string i9_resident_status { get; set; }
        public short? earned_income_credit { get; set; }
        public string alien_admin_num { get; set; }
        public DateTime? expiration_date { get; set; }
        public string reg_disable_num { get; set; }
        public string ob_temporary_emp { get; set; }
        public string ob_emp_live_on_property { get; set; }
        public string ob_exclude_EU_directives { get; set; }
        public DateTime? original_hire_date { get; set; }
        public string bank_acct_number { get; set; }
        public string bank_2_acct_num { get; set; }
        public decimal? bank_amt { get; set; }
        public decimal? bank_2_amt { get; set; }
        public string bank_amt_type { get; set; }
        public string bank_2_amt_type { get; set; }
        public string ob_bank_balance { get; set; }
        public string ob_bank_2_balance { get; set; }
        public string work_permit_number { get; set; }
        public DateTime? work_permit_expiration_date { get; set; }
        public string age_cert_num { get; set; }
        public DateTime? age_cert_date { get; set; }
        public string transfer_from_store { get; set; }
        public string bank_sort_code { get; set; }
        public string bank_2_routing_code { get; set; }
        public string bank_acct_type { get; set; }
        public string bank_2_acct_type { get; set; }
        public string hire_status { get; set; }
        public int? inactive_reason_seq { get; set; }
        public DateTime? inactive_from_date { get; set; }
        public DateTime? inactive_to_date { get; set; }
        public string transfer_to_store { get; set; }
        public DateTime? salary_start_date { get; set; }
        public decimal? hourly_salary { get; set; }
        public decimal? daily_salary { get; set; }
        public decimal? weekly_salary { get; set; }
        public decimal? four_week_salary { get; set; }
        public decimal? monthly_salary { get; set; }
        public decimal? annual_salary { get; set; }
        public string salary_rate_type { get; set; }
        public string ob_sub_min_wage_pay { get; set; }
        public string ob_veteran_disabled { get; set; }
        public DateTime? termination_date { get; set; }
        public string termination_status { get; set; }
        public int? termination_reason_1_seq { get; set; }
        public int? termination_reason_2_seq { get; set; }
        public int? termination_reason_3_seq { get; set; }
        public int? termination_reason_4_seq { get; set; }
        public string termination_note { get; set; }
        public string alpha_01 { get; set; }
        public string alpha_02 { get; set; }
        public string alpha_03 { get; set; }
        public string alpha_04 { get; set; }
        public string alpha_05 { get; set; }
        public string alpha_06 { get; set; }
        public string alpha_07 { get; set; }
        public string alpha_08 { get; set; }
        public decimal? numeric_01 { get; set; }
        public decimal? numeric_02 { get; set; }
        public decimal? numeric_03 { get; set; }
        public decimal? numeric_04 { get; set; }
        public decimal? numeric_05 { get; set; }
        public decimal? numeric_06 { get; set; }
        public decimal? numeric_07 { get; set; }
        public decimal? numeric_08 { get; set; }
        public string emp_photo_filename { get; set; }
        public string note { get; set; }
        public string html { get; set; }
        public short? lds_id { get; set; }
        public string ob_bravo_configurator { get; set; }
        public int? last_updated_by { get; set; }
        public DateTime? last_updated_date { get; set; }
        public int? ob_flags { get; set; }
        public string ob_frgn_part_time_student { get; set; }
        public string ob_frgn_full_time_student { get; set; }
        public string user_id { get; set; }
        public string ob_account_disabled { get; set; }
        public string ob_change_password { get; set; }
        public int? login_attempts { get; set; }
        public string em_guid { get; set; }
        public short em_mgmt_state { get; set; }
        public string ob_emp_override_fp_req { get; set; }
        public string os_user_name { get; set; }
        public string os_domain_name { get; set; }
        public string military_status { get; set; }
        public string exempt { get; set; }
        public string ob_seasonal { get; set; }
        public string wotc_cd { get; set; }
        public string emp_mode { get; set; }
        public short? pay_type { get; set; }
        public string dda_number { get; set; }
        public DateTime? esr_effdt { get; set; }
        public short? duration_days { get; set; }
        public DateTime? va_begin_dt { get; set; }
        public DateTime? va_return_dt { get; set; }
        public int? jobcode { get; set; }
        public decimal? rate { get; set; }
        public string oldssn { get; set; }
        public DateTime? business_date { get; set; }
    }
}
