using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class order_type_def
    {
        public int order_type_seq { get; set; }
        public string name { get; set; }
        public string ob_ot01_active { get; set; }
        public string ob_ot02_prn_on_rcpt_or_chk { get; set; }
        public string ob_ot03_prn_on_order_chit { get; set; }
        public string ob_ot04_disp_on_vdu { get; set; }
        public string ob_no_post_tip_ttls { get; set; }
        public string ob_uk_take_out_vat_tax { get; set; }
        public string ob_auto_combo_recognition { get; set; }
        public string ob_rsvd02 { get; set; }
        public string ob_rsvd03 { get; set; }
        public string ob_rsvd04 { get; set; }
        public string ob_rsvd05 { get; set; }
        public string ob_rsvd06 { get; set; }
        public int? tax_class_seq { get; set; }
        public int? last_updated_by { get; set; }
        public DateTime? last_updated_date { get; set; }
        public string ob_drive_thru_ot { get; set; }
        public int? cond_grp_mask_01 { get; set; }
        public int? cond_grp_mask_02 { get; set; }
        public string ob_forgive_incl_tax { get; set; }
        public string ob_rsvd_10 { get; set; }
        public int? cond_grp_mask_03 { get; set; }
        public int? cond_grp_mask_04 { get; set; }
        public int? cond_grp_mask_05 { get; set; }
        public int? cond_grp_mask_06 { get; set; }
        public int? cond_grp_mask_07 { get; set; }
        public int? cond_grp_mask_08 { get; set; }
        public string ob_gss_delivery { get; set; }
        public int? future_order_offset { get; set; }
        public int? ts_dd_pickup_seq { get; set; }
        public string ob_suppress_dining_course { get; set; }
        public string ob_need_container { get; set; }
        public string ob_track_for_tips { get; set; }
        public string ob_gss_takeout { get; set; }
        public string ob_disable_placeholder_prompt { get; set; }
        public string ob_suppress_prt_gst_chk { get; set; }
        public string ob_suppress_prt_ca_vchr { get; set; }
        public string ob_disable_placeholder_immed { get; set; }
        public int? kds_highlight_scheme_seq { get; set; }
        public string ob_gss_carside { get; set; }
        public string ob_prompt_for_promise_time { get; set; }
        public int? promise_time_adj_expire_minutes { get; set; }
        public string ob_enable_ordr_dev_01 { get; set; }
        public string ob_enable_ordr_dev_02 { get; set; }
        public string ob_enable_ordr_dev_03 { get; set; }
        public string ob_enable_ordr_dev_04 { get; set; }
        public string ob_enable_ordr_dev_05 { get; set; }
        public string ob_enable_ordr_dev_06 { get; set; }
        public string ob_enable_ordr_dev_07 { get; set; }
        public string ob_enable_ordr_dev_08 { get; set; }
        public string ob_enable_ordr_dev_09 { get; set; }
        public string ob_enable_ordr_dev_10 { get; set; }
        public string ob_enable_ordr_dev_11 { get; set; }
        public string ob_enable_ordr_dev_12 { get; set; }
        public string ob_enable_ordr_dev_13 { get; set; }
        public string ob_enable_ordr_dev_14 { get; set; }
        public string ob_enable_ordr_dev_15 { get; set; }
        public string ob_enable_ordr_dev_16 { get; set; }
        public string ob_enable_ordr_dev_17 { get; set; }
        public string ob_enable_ordr_dev_18 { get; set; }
        public string ob_enable_ordr_dev_19 { get; set; }
        public string ob_enable_ordr_dev_20 { get; set; }
        public string ob_enable_ordr_dev_21 { get; set; }
        public string ob_enable_ordr_dev_22 { get; set; }
        public string ob_enable_ordr_dev_23 { get; set; }
        public string ob_enable_ordr_dev_24 { get; set; }
        public string ob_enable_ordr_dev_25 { get; set; }
        public string ob_enable_ordr_dev_26 { get; set; }
        public string ob_enable_ordr_dev_27 { get; set; }
        public string ob_enable_ordr_dev_28 { get; set; }
        public string ob_enable_ordr_dev_29 { get; set; }
        public string ob_enable_ordr_dev_30 { get; set; }
        public string ob_enable_ordr_dev_31 { get; set; }
        public string ob_enable_ordr_dev_32 { get; set; }
        public string ob_disable_bvg_ctrl { get; set; }
        public string ob_print_item_all_prep_done { get; set; }
        public int? cook_time_multiplier { get; set; }
        public int? recent_prep_time_chk_cnt { get; set; }
        public int? recent_prep_time_chk_min { get; set; }
        public string ob_disable_promise_time_delay { get; set; }
        public string ob_prn_multiple_gst_chks { get; set; }
        public string ob_prompt_prn_multi_gst_chks { get; set; }
        public string ob_enable_ordr_dev_alt_01 { get; set; }
        public string ob_enable_ordr_dev_alt_02 { get; set; }
        public string ob_enable_ordr_dev_alt_03 { get; set; }
        public string ob_enable_ordr_dev_alt_04 { get; set; }
        public string ob_enable_ordr_dev_alt_05 { get; set; }
        public string ob_enable_ordr_dev_alt_06 { get; set; }
        public string ob_enable_ordr_dev_alt_07 { get; set; }
        public string ob_enable_ordr_dev_alt_08 { get; set; }
        public string ob_enable_ordr_dev_alt_09 { get; set; }
        public string ob_enable_ordr_dev_alt_10 { get; set; }
        public string ob_enable_ordr_dev_alt_11 { get; set; }
        public string ob_enable_ordr_dev_alt_12 { get; set; }
        public string ob_enable_ordr_dev_alt_13 { get; set; }
        public string ob_enable_ordr_dev_alt_14 { get; set; }
        public string ob_enable_ordr_dev_alt_15 { get; set; }
        public string ob_enable_ordr_dev_alt_16 { get; set; }
        public string ob_enable_ordr_dev_alt_17 { get; set; }
        public string ob_enable_ordr_dev_alt_18 { get; set; }
        public string ob_enable_ordr_dev_alt_19 { get; set; }
        public string ob_enable_ordr_dev_alt_20 { get; set; }
        public string ob_enable_ordr_dev_alt_21 { get; set; }
        public string ob_enable_ordr_dev_alt_22 { get; set; }
        public string ob_enable_ordr_dev_alt_23 { get; set; }
        public string ob_enable_ordr_dev_alt_24 { get; set; }
        public string ob_enable_ordr_dev_alt_25 { get; set; }
        public string ob_enable_ordr_dev_alt_26 { get; set; }
        public string ob_enable_ordr_dev_alt_27 { get; set; }
        public string ob_enable_ordr_dev_alt_28 { get; set; }
        public string ob_enable_ordr_dev_alt_29 { get; set; }
        public string ob_enable_ordr_dev_alt_30 { get; set; }
        public string ob_enable_ordr_dev_alt_31 { get; set; }
        public string ob_enable_ordr_dev_alt_32 { get; set; }
        public string abbrev { get; set; }
        public string ob_display_future_orders { get; set; }
        public string ob_display_delayed_orders { get; set; }
        public short? dispatch_lockout { get; set; }
        public string ob_require_dispatch { get; set; }
        public short? dispatch_bonus_secs { get; set; }
        public short? dispatch_bonus_secs_bev_only { get; set; }
        public string ob_stall_ot { get; set; }
        public int? std_expo_tray_area_seq { get; set; }
        public int? bev_expo_tray_area_seq { get; set; }
        public int? override_print_profile_uws_seq { get; set; }
        public string ob_xfer_chk_during_pickup { get; set; }
        public string ob_require_greeting { get; set; }
        public string ob_allow_manual_dispatch { get; set; }
        public short? alert_schema_pos { get; set; }
        public short? alert_schema_kds { get; set; }
        public string ob_post_tip_ttls_if_tip { get; set; }
        public string ob_post_tip_ttls_if_tip_all_td { get; set; }
    }
}
