using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class order_device_def
    {
        public int ord_dvc_seq { get; set; }
        public string name { get; set; }
        public int? hdr_seq { get; set; }
        public int? order_device { get; set; }
        public int? backup_prntr { get; set; }
        public int? redirect { get; set; }
        public int? kds_backup_ord_dvc_seq { get; set; }
        public string ob_rod01_dont_sort { get; set; }
        public string ob_rod02_donot_consol { get; set; }
        public string ob_rod03_multi_cond_per_line { get; set; }
        public string ob_rod04_multi_cond_in_red { get; set; }
        public string ob_rod05_sort_by_seat { get; set; }
        public string ob_rod06_prn_seat_line_red { get; set; }
        public string ob_rod07_print_dopple_chit { get; set; }
        public string ob_rod08_disp_seat_num { get; set; }
        public string ob_rod09_incl_sos_info_hdr { get; set; }
        public string ob_rod12_show_scndary_items { get; set; }
        public string ob_rod13_enbl_scndry_prn_hdr { get; set; }
        public string ob_rod14_scndry_items_in_red { get; set; }
        public string ob_rod15_supress_blank_lines { get; set; }
        public string ob_rod16_send_to_other_prn { get; set; }
        public string ob_rod_prn_line_by_line { get; set; }
        public string ob_rod_table_num_at_end { get; set; }
        public string ob_vdu03_order_timer { get; set; }
        public string ob_vdu04_key_beep_active { get; set; }
        public string ob_vdu05_order_beep_active { get; set; }
        public string ob_kds_consolidate { get; set; }
        public string ob_print_all_prep_done { get; set; }
        public int? beep_on_new_order { get; set; }
        public int? dyn_order_mode_type { get; set; }
        public string ob_display_sttl { get; set; }
        public string ob_display_cncl_order { get; set; }
        public string ob_notify_of_payment { get; set; }
        public string ob_do_not_sort_cond { get; set; }
        public string ob_display_mi_cnt { get; set; }
        public string ob_do_not_display_voids { get; set; }
        public string ob_unconsol_after_cond { get; set; }
        public string ob_dyn_order_mode { get; set; }
        public int? panel_output { get; set; }
        public string ob_display_new_order { get; set; }
        public int? new_order_time { get; set; }
        public int? sos_tbl_dtl_time { get; set; }
        public string chk_info_prn_format { get; set; }
        public short? vdu_timeout { get; set; }
        public string vdu_scrn_cfg { get; set; }
        public int? kds_app_alert1 { get; set; }
        public int? kds_app_alert2 { get; set; }
        public int? kds_other_alert1 { get; set; }
        public int? kds_other_alert2 { get; set; }
        public int? event_prior_add_sort { get; set; }
        public int? event_prior_mod_sort { get; set; }
        public int? event_prior_void_sort { get; set; }
        public int? event_prior_add_highlight { get; set; }
        public int? event_prior_mod_highlight { get; set; }
        public int? event_prior_void_highlight { get; set; }
        public string ob_kds_sort_voids_to_top { get; set; }
        public string ob_kds_change_priority_APD { get; set; }
        public string ob_kds_print_on_expo_done { get; set; }
        public string ob_kds_print_on_prep_done { get; set; }
        public string ob_kds_allow_marked_bumped { get; set; }
        public string str_kds_rsvd { get; set; }
        public string ob_rsvd06 { get; set; }
        public string ob_rsvd07 { get; set; }
        public string ob_print_seat_num_on_MI { get; set; }
        public string ob_always_show_qty { get; set; }
        public string ob_rsvd10 { get; set; }
        public string ob_rsvd11 { get; set; }
        public string ob_rsvd12 { get; set; }
        public string ob_rsvd13_cons_combo_items { get; set; }
        public string ob_kds_rsvd01 { get; set; }
        public string ob_kds_rsvd02 { get; set; }
        public string ob_deli_chit { get; set; }
        public string ob_disable_dbl_bump { get; set; }
        public int? num_kds_rsvd01 { get; set; }
        public int? num_kds_rsvd02 { get; set; }
        public int? num_kds_rsvd03 { get; set; }
        public int? num_kds_rsvd04 { get; set; }
        public string str_kds_rsvd01 { get; set; }
        public string str_kds_rsvd02 { get; set; }
        public string str_kds_rsvd03 { get; set; }
        public string str_kds_rsvd04 { get; set; }
        public int? last_updated_by { get; set; }
        public DateTime? last_updated_date { get; set; }
        public string ob_kds_single_item_per_so { get; set; }
        public int? ord_dvc_link_01 { get; set; }
        public int? ord_dvc_link_02 { get; set; }
        public int? ord_dvc_link_03 { get; set; }
        public int? ord_dvc_link_04 { get; set; }
        public int? ord_dvc_link_05 { get; set; }
        public int? ord_dvc_link_06 { get; set; }
        public int? ord_dvc_link_07 { get; set; }
        public int? ord_dvc_link_08 { get; set; }
        public string ob_do_not_sort { get; set; }
        public string ob_print_course_header { get; set; }
        public int? kds_chit_printer { get; set; }
        public int? kds_backup_chit_printer { get; set; }
        public string gst_info_print_format { get; set; }
        public string delv_info_print_format { get; set; }
        public string delv_note_print_format { get; set; }
        public string delv_time_print_format { get; set; }
        public int? trlr_seq { get; set; }
        public string override_name_to_print { get; set; }
        public short? consol_mode { get; set; }
        public string ob_sort_all_condiments { get; set; }
        public string ob_print_specialty_toppings { get; set; }
        public string ob_rmt_prefix_on_condiment_line { get; set; }
        public string ob_prefix_uses_cond_print_grp { get; set; }
        public string ob_include_default_condiments { get; set; }
        public string rod_info_print_format { get; set; }
        public string ob_suppress_guest_check_id { get; set; }
        public string ob_kds_print_chk_on_expo_done { get; set; }
        public string ob_kds_print_ca_on_expo_done { get; set; }
        public string ob_suppress_check_total { get; set; }
        public string promise_time_print_format { get; set; }
        public string ob_no_prep_done_before_paid { get; set; }
        public string ob_kds_alerts_based_on_sent_tm { get; set; }
        public int? add_to_order_hdr_seq { get; set; }
        public string ob_print_gss_info_on_chit { get; set; }
        public string ob_expo_done_exempt { get; set; }
        public string ob_print_item_all_prep_done { get; set; }
        public string ob_rod_mi_consol_fpm_course { get; set; }
        public int? beep_on_vip_order { get; set; }
        public int? beep_on_rush_order { get; set; }
        public int? beep_on_prioritize_order { get; set; }
        public string ob_show_print_grp_labels { get; set; }
        public string ob_match_voids_w_orders { get; set; }
        public int? primary_distribution_group_seq { get; set; }
        public string ob_rod_expand_menu_items { get; set; }
        public int? alt_kds_app_alert1 { get; set; }
        public int? alt_kds_app_alert2 { get; set; }
        public int? alt_kds_other_alert1 { get; set; }
        public int? alt_kds_other_alert2 { get; set; }
        public string ob_kds_alerts_based_on_greet_tm { get; set; }
        public string ob_kds_alerts_based_on_sent_tm1 { get; set; }
        public string ob_kds_alerts_based_on_greet_t1 { get; set; }
    }
}
