using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class rest_def
    {
        public int store_id { get; set; }
        public int? fed_state_law_seq { get; set; }
        public string rest_name { get; set; }
        public int obj_num { get; set; }
        public string location_name_1 { get; set; }
        public string location_name_2 { get; set; }
        public int? server_lan_node_seq { get; set; }
        public int? backup_server_lan_node_seq { get; set; }
        public int? lang_seq { get; set; }
        public string addr_line_1 { get; set; }
        public string addr_line_2 { get; set; }
        public string addr_city { get; set; }
        public string addr_state { get; set; }
        public string addr_postal_code { get; set; }
        public string addr_cntry { get; set; }
        public string phone_1 { get; set; }
        public string phone_2 { get; set; }
        public string comments { get; set; }
        public string non_txbl_name { get; set; }
        public string local_cncy_name { get; set; }
        public string local_cncy_desc { get; set; }
        public short local_cncy_decimal_places { get; set; }
        public string local_cncy_decimal_char { get; set; }
        public string local_cncy_thousands_char { get; set; }
        public int? euro_or_alt_cncy_seq { get; set; }
        public string pos_type { get; set; }
        public short bus_day_start_tm { get; set; }
        public short bus_wk_start_day { get; set; }
        public DateTime? fiscal_start_date { get; set; }
        public string fiscal_period_type { get; set; }
        public string fiscal_period_name { get; set; }
        public short num_days_save_batches { get; set; }
        public string deflt_prntr_name { get; set; }
        public int? mp_deflt_info_scrn_seq { get; set; }
        public int? mr_deflt_info_scrn_seq { get; set; }
        public int? rw_deflt_info_scrn_seq { get; set; }
        public string ob_rvc009_us_tax { get; set; }
        public string ob_rvc017_euro_date { get; set; }
        public string ob_rvc018_euro_time { get; set; }
        public string ob_rvc022_singapore_tax { get; set; }
        public string ob_rvc024_weight_in_kgs { get; set; }
        public string ob_rvc089_enable_canada_tax { get; set; }
        public string ob_rvc138_fla_tax_surcharge { get; set; }
        public string ob_alloc_mi_dtl_ttls { get; set; }
        public string ob_emp_opt_allocated { get; set; }
        public string ob_prn_all_digits { get; set; }
        public string ob_float_fiscal_start_date { get; set; }
        public string ob_float_prd_day_of_wk { get; set; }
        public string ob_autoincr_business_date { get; set; }
        public string ob_enable_thai_tax { get; set; }
        public string ob_enable_taiwan_gui { get; set; }
        public string ob_taiwan_gui_sys_level { get; set; }
        public string ob_enable_japan_tax { get; set; }
        public string ob_round_japan { get; set; }
        public string ob_euro_transition_phase { get; set; }
        public string ob_euro_is_local_cncy { get; set; }
        public string ob_change_in_alt_cncy { get; set; }
        public string ob_rsvd01 { get; set; }
        public string ob_rsvd02 { get; set; }
        public string ob_rsvd03 { get; set; }
        public string ob_rsvd04 { get; set; }
        public string ob_rsvd05 { get; set; }
        public string ob_rsvd06 { get; set; }
        public string ob_rsvd07 { get; set; }
        public string user_dfn_1 { get; set; }
        public string user_dfn_2 { get; set; }
        public string user_dfn_3 { get; set; }
        public string user_dfn_4 { get; set; }
        public string user_dfn_5 { get; set; }
        public short? barcode_nlu_grp { get; set; }
        public string em_store_rcv_addr { get; set; }
        public string em_store_send_addr { get; set; }
        public string em_corp_rcv_addr { get; set; }
        public string em_corp_send_addr { get; set; }
        public string em_rest_active_status { get; set; }
        public short? disk_full_threshold { get; set; }
        public string taiwan_tax_num_prefix { get; set; }
        public short? taiwan_end_range_threshold { get; set; }
        public short? lds_recs_allocated { get; set; }
        public short? lds_nlu_grp { get; set; }
        public short? prntr_buffer_recs_allocated { get; set; }
        public short? sim1_recs_allocated { get; set; }
        public short? sim2_recs_allocated { get; set; }
        public short? sim_data_recs_allocated { get; set; }
        public short? ochk_ttl_recs_allocated { get; set; }
        public short? ochk_dtl_blks_allocated { get; set; }
        public short? cchk_ttl_recs_allocated { get; set; }
        public short? min_itb_recs_allocated { get; set; }
        public int? su_trk_grp_seq { get; set; }
        public int? scnd_su_trk_grp_seq { get; set; }
        public short? excl_pt_map_char { get; set; }
        public short? dbl_quote_map_char { get; set; }
        public short? dollar_sign_map_char { get; set; }
        public short? less_than_map_char { get; set; }
        public short? greater_than_map_char { get; set; }
        public short? backslash_map_char { get; set; }
        public short? business_autoincr_offset { get; set; }
        public int? lite_cc_type { get; set; }
        public string ob_euro_short_alt_cncy_ttls { get; set; }
        public string ob_euro_alt_cncy_ttls_first { get; set; }
        public string ob_retail_items { get; set; }
        public string employer_id { get; set; }
        public int? work_hrs_seq { get; set; }
        public int? fcst_ele_seq { get; set; }
        public string html { get; set; }
        public short emp_access_lvl { get; set; }
        public int? last_updated_by { get; set; }
        public DateTime? last_updated_date { get; set; }
        public string ob_enable_item_vat_tax { get; set; }
        public string ob_vat_by_the_round { get; set; }
        public string ob_uk_cash_back_enabled { get; set; }
        public string ob_no_edit_prev_day_chk { get; set; }
        public string ob_australian_gst_active { get; set; }
        public decimal? gst_prompt_threshold { get; set; }
        public string ob_use_thousands_separator_char { get; set; }
        public string ob_tid_enable { get; set; }
        public string ob_cc_secure_track_data { get; set; }
        public string ob_cc_encrypt_data { get; set; }
        public string local_qty_descriptor { get; set; }
        public string local_piece_descriptor { get; set; }
        public string ob_print_currency_symbol { get; set; }
        public string ob_alt_media_server { get; set; }
        public string alt_media_server { get; set; }
        public int? tax_juris_seq { get; set; }
        public string ob_classic_security { get; set; }
        public int? max_failed_logins { get; set; }
        public int? pwd_repeat_int { get; set; }
        public int? min_pwd_len { get; set; }
        public string req_alphanum_pwd { get; set; }
        public int? days_until_exp { get; set; }
        public int? max_idle_time { get; set; }
        public string ob_oldest_batch_first { get; set; }
        public byte[] install_code { get; set; }
        public decimal? tip_chk_percent { get; set; }
        public string ob_suppress_rvc_clk_out { get; set; }
        public byte? min_id_length { get; set; }
        public string ob_fp_only_enroll_signin_emp { get; set; }
        public string ob_enable_integrated_logon { get; set; }
        public string faied_integrated_logon_msg { get; set; }
        public string ob_no_disp_prt_pm_waste_price { get; set; }
        public string ob_vat_by_rnd_add_net_sls { get; set; }
        public string ob_tip_share { get; set; }
        public string ob_tip_TRAC { get; set; }
        public decimal? tip_TRAC_cash_percent { get; set; }
        public decimal? tip_TRAC_credit_percent { get; set; }
        public string ob_clk_out_decl_tips_only { get; set; }
        public string ob_esr_enabled { get; set; }
        public string ob_rvc_weight_in_ounces { get; set; }
        public string ob_enable_srm { get; set; }
        public string ob_EMSR_mode { get; set; }
        public string ob_rvc_weight_in_grams { get; set; }
        public UInt16? num_expo_trays { get; set; }
        public string ob_enable_early_drive_thru_expo { get; set; }
        public short? early_drive_thru_expo_start_tm { get; set; }
        public short? early_drive_thru_expo_end_tm { get; set; }
        public UInt16? early_drive_thru_expo_min_pos { get; set; }
        public UInt16? early_drive_thru_expo_keep_sec { get; set; }
        public int? early_dt_expo_period1_seq { get; set; }
        public int? early_dt_expo_period2_seq { get; set; }
        public int? early_dt_expo_period3_seq { get; set; }
        public int? early_dt_expo_period4_seq { get; set; }
        public string ob_assign_expo_tray_at_start { get; set; }
        public string weighed_mi_net_weight_label { get; set; }
        public string ob_reset_chk_num_with_bus_date { get; set; }
        public string ob_disp_chk_ttl_after_item_ttl { get; set; }
        public string ob_disp_scale_cert_number { get; set; }
        public int? prevent_emp_anonymization_days { get; set; }
        public string ob_prompt_for_consent { get; set; }
        public string customer_consent_text { get; set; }
        public int? Prevent_emp_delete_days { get; set; }
        public string ob_secure_dbbackup { get; set; }
        public string ob_always_print_quantity { get; set; }
        public string ob_autoincr_cashier_shift { get; set; }
        public string ob_autoincr_emp_shift { get; set; }
    }
}
