using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class rvc_def
    {
        public int rvc_seq { get; set; }
        public int? srv_period_seq { get; set; }
        public int? not_in_file_slu { get; set; }
        public int obj_num { get; set; }
        public string name { get; set; }
        public int? cash_tmed_seq { get; set; }
        public int? bank_tmed_seq { get; set; }
        public int? auto_dsvc_seq { get; set; }
        public decimal? med_decl_over_short_amt { get; set; }
        public short start_chk_num { get; set; }
        public short end_chk_num { get; set; }
        public string ob_rvc001_usr_assign_chk_num { get; set; }
        public string ob_rvc005_allow_fast_trans { get; set; }
        public string ob_rvc007_fast_tran_svc { get; set; }
        public string ob_rvc010_prn_zero_vat_chk { get; set; }
        public string ob_rvc011_consol_vat_on_chk { get; set; }
        public string ob_rvc012_prn_net_vat_on_chk { get; set; }
        public string ob_rvc019_rnd_dsvc { get; set; }
        public string ob_rvc020_rnd_zero_tens { get; set; }
        public string ob_rvc021_rnd_tens_digit { get; set; }
        public string ob_rvc025_one_open_chk_per { get; set; }
        public string ob_rvc030_id_on_tip_entry { get; set; }
        public string ob_rvc031_id_for_emp_meal { get; set; }
        public string ob_rvc032_id_begin_others { get; set; }
        public string ob_rvc033_cshr_req_all_trans { get; set; }
        public string ob_rvc034_cshr_req_media_tip { get; set; }
        public string ob_rvc035_ttls_to_chk_cshr { get; set; }
        public string ob_rvc036_dont_confirm_begin { get; set; }
        public string ob_rvc037_no_confirm_pickup { get; set; }
        public string ob_rvc046_req_full_pymnt { get; set; }
        public string ob_rvc049_dont_pop_main_mlvl { get; set; }
        public string ob_rvc050_dont_pop_sub_mlvl { get; set; }
        public string ob_rvc052_tax_exempt_ref_req { get; set; }
        public string ob_rvc053_no_tax_tip_rcpts { get; set; }
        public string ob_rvc056_open_drw_if_0_chng { get; set; }
        public string ob_rvc062_cov_as_svc { get; set; }
        public string ob_rvc083_prn_vat_pre_subttl { get; set; }
        public string ob_rvc086_enable_seats { get; set; }
        public string ob_rvc087_default_to_seat_1 { get; set; }
        public string ob_rvc088_chk_seat_with_cov { get; set; }
        public string ob_rvc090_prn_canada_tax_sep { get; set; }
        public string ob_rvc091_prn_canad_txbl_amt { get; set; }
        public string ob_rvc092_combine_PST_3 { get; set; }
        public string ob_rvc093_combine_PST_4 { get; set; }
        public string ob_rvc095_use_seat_cov_cnt { get; set; }
        public string ob_rvc096_keep_seat_num_add { get; set; }
        public string ob_rvc098_auto_svc_deflt_off { get; set; }
        public string ob_rvc102_id_on_blk_chk_xfer { get; set; }
        public string ob_rvc103_neg_trans_no_cov { get; set; }
        public string ob_rvc104_warn_pc_inactive { get; set; }
        public string ob_rvc105_rnd_ttl_due { get; set; }
        public string ob_rvc106_rnd_ttl_to_tens { get; set; }
        public string ob_rvc107_rnd_ttl_tens_digit { get; set; }
        public string ob_rvc108_bev_ctrl { get; set; }
        public string ob_rvc109_bev_ctrl_by_cov { get; set; }
        public string ob_rvc112_disp_cshr_name { get; set; }
        public string ob_rvc113_lds_fast_trans { get; set; }
        public string ob_rvc115_post_rnd_trans_emp { get; set; }
        public string ob_rvc127_allow_tbl_chaining { get; set; }
        public string ob_rvc130_post_ot_ttl_at_tnd { get; set; }
        public string ob_rvc132_post_gross_to_ot { get; set; }
        public string ob_rvc137_no_lmt_macro_chain { get; set; }
        public string ob_rvc142_req_pos_tip_decl { get; set; }
        public string ob_rvc144_void_edit { get; set; }
        public string ob_rvc145_omit_prev_crs_seat { get; set; }
        public string ob_rvc152_suspend_resume { get; set; }
        public string ob_rvc153_resume_search_lcl { get; set; }
        public string ob_rvc157_mi_sls_to_maj_grp { get; set; }
        public string ob_rvc161_no_multi_sign_in { get; set; }
        public string ob_rvc165_mi_cnt_cache { get; set; }
        public string ob_rw02_french_vat_reporting { get; set; }
        public string ob_rw03_reset_cshr_emp_bal { get; set; }
        public string ob_rw04_reset_drwr_emp_bal { get; set; }
        public string ob_rw06_prn_pst_sttl { get; set; }
        public string ob_rw07_prn_resets_to_jnl { get; set; }
        public string ob_rw08_reset_cnt_on_rpts { get; set; }
        public string ob_rw09_suprs_prfl_sys_bal { get; set; }
        public string ob_rw10_suprs_prfl_rvc_bal { get; set; }
        public string ob_rw11_suprs_prfl_emp_bal { get; set; }
        public string ob_rw12_suprs_prfl_cshr_bal { get; set; }
        public string ob_rw13_suprs_tbl_prfl { get; set; }
        public string ob_rw14_suprs_grand_ttl { get; set; }
        public string ob_rw15_omit_trk_grp_names { get; set; }
        public string ob_rw16_partial_cut_rpts { get; set; }
        public string ob_rw25_prn_media_decl_chit { get; set; }
        public string ob_rw26_media_decl_sys_scope { get; set; }
        public string ob_rw27_media_decl_rvc_scope { get; set; }
        public string ob_rw28_media_decl_su_scope { get; set; }
        public string ob_rw31_trk_grp_excptn { get; set; }
        public string ob_rw33_reset_cshr_rvc_bal { get; set; }
        public string ob_rw35_trk_ttl_carry_over { get; set; }
        public string ob_use_1st_avail_grp { get; set; }
        public string ob_verify_sku_check_digit { get; set; }
        public string ob_sku_display_and_print { get; set; }
        public string ob_prompt_price_override_ref { get; set; }
        public string ob_thai_tax_use_uws_num { get; set; }
        public string ob_verify_fcr_before_chk { get; set; }
        public string ob_disp_subttl_after_ot_decl { get; set; }
        public string ob_no_post_tip_ttls { get; set; }
        public string ob_upce_to_upca { get; set; }
        public string ob_upc_check_digit { get; set; }
        public string ob_enable_not_in_file_help { get; set; }
        public string ob_tax_on_florida_surcharge { get; set; }
        public string ob_enable_ean { get; set; }
        public string ob_barcode_help { get; set; }
        public string ob_disable_mi_nlu_help { get; set; }
        public string ob_allow_svcttl_on_clsd_chk { get; set; }
        public string ob_dyn_order_mode { get; set; }
        public string ob_enable_sprd { get; set; }
        public short? num_sign_in_keys { get; set; }
        public short? num_days_chk_dtl { get; set; }
        public string tax_name { get; set; }
        public string other_svc_chg_name { get; set; }
        public string seat_name { get; set; }
        public string cshr_name { get; set; }
        public string sign_in_cshr_prompt { get; set; }
        public int? emp_dsc_trlr { get; set; }
        public int? canada_tax_trlr_1 { get; set; }
        public int? canada_tax_trlr_2 { get; set; }
        public short? trans_main_lvl { get; set; }
        public short? trans_sub_lvl { get; set; }
        public string print_vat_1_on_chk { get; set; }
        public string print_vat_2_on_chk { get; set; }
        public string print_vat_3_on_chk { get; set; }
        public string print_vat_4_on_chk { get; set; }
        public string print_vat_5_on_chk { get; set; }
        public string print_vat_6_on_chk { get; set; }
        public string print_vat_7_on_chk { get; set; }
        public string print_vat_8_on_chk { get; set; }
        public short max_detail_entries { get; set; }
        public string main_mlvl_1_name { get; set; }
        public string main_mlvl_2_name { get; set; }
        public string main_mlvl_3_name { get; set; }
        public string main_mlvl_4_name { get; set; }
        public string main_mlvl_5_name { get; set; }
        public string main_mlvl_6_name { get; set; }
        public string main_mlvl_7_name { get; set; }
        public string main_mlvl_8_name { get; set; }
        public string main_mlvl_9_name { get; set; }
        public string main_mlvl_10_name { get; set; }
        public string sub_mlvl_1_name { get; set; }
        public string sub_mlvl_2_name { get; set; }
        public string sub_mlvl_3_name { get; set; }
        public string sub_mlvl_4_name { get; set; }
        public string sub_mlvl_5_name { get; set; }
        public string sub_mlvl_6_name { get; set; }
        public string sub_mlvl_7_name { get; set; }
        public string sub_mlvl_8_name { get; set; }
        public string sub_mlvl_9_name { get; set; }
        public string sub_mlvl_10_name { get; set; }
        public string main_mlvl_1_prefix { get; set; }
        public string main_mlvl_2_prefix { get; set; }
        public string main_mlvl_3_prefix { get; set; }
        public string main_mlvl_4_prefix { get; set; }
        public string main_mlvl_5_prefix { get; set; }
        public string main_mlvl_6_prefix { get; set; }
        public string main_mlvl_7_prefix { get; set; }
        public string main_mlvl_8_prefix { get; set; }
        public string main_mlvl_9_prefix { get; set; }
        public string main_mlvl_10_prefix { get; set; }
        public string sub_mlvl_1_prefix { get; set; }
        public string sub_mlvl_2_prefix { get; set; }
        public string sub_mlvl_3_prefix { get; set; }
        public string sub_mlvl_4_prefix { get; set; }
        public string sub_mlvl_5_prefix { get; set; }
        public string sub_mlvl_6_prefix { get; set; }
        public string sub_mlvl_7_prefix { get; set; }
        public string sub_mlvl_8_prefix { get; set; }
        public string sub_mlvl_9_prefix { get; set; }
        public string sub_mlvl_10_prefix { get; set; }
        public string taiwan_tax_num_prefix { get; set; }
        public short? taiwan_end_range_threshold { get; set; }
        public string thai_tax_tin_line { get; set; }
        public string thai_tax_rvc_rd_num_line { get; set; }
        public int? lds_dev_seq { get; set; }
        public short? trans_buffer_warn_lvl { get; set; }
        public int? su_trk_grp_seq { get; set; }
        public int? scnd_su_trk_grp_seq { get; set; }
        public int? work_hrs_seq { get; set; }
        public int? fcst_ele_seq { get; set; }
        public string ob_print_check_on_xfer { get; set; }
        public string ob_print_ca_voucher_on_xfer { get; set; }
        public string ob_print_xfer_list_rpt { get; set; }
        public string ob_dispatch_uses_kds { get; set; }
        public string ob_allow_mi_void_clsd_chk { get; set; }
        public string ob_print_lb_weight_with_2_dp { get; set; }
        public string ob_rsvd08 { get; set; }
        public string ob_rsvd09 { get; set; }
        public string ob_rsvd10 { get; set; }
        public string ob_rsvd11 { get; set; }
        public string ob_rsvd12 { get; set; }
        public string ob_rsvd13 { get; set; }
        public int? last_updated_by { get; set; }
        public DateTime? last_updated_date { get; set; }
        public string ob_auto_complete_cndmnt { get; set; }
        public string ob_assume_max_cndmnt { get; set; }
        public int? ob_flags { get; set; }
        public string ob_rnd_gst_total_up { get; set; }
        public short insignificant_digits { get; set; }
        public short insignificant_digits_dsvc { get; set; }
        public string ob_dd_reopen_closed_check { get; set; }
        public string ob_dom_send_before_mi_complete { get; set; }
        public string ob_continue_courses { get; set; }
        public string ob_automatic_discounting { get; set; }
        public string ob_conversational_ordering_mode { get; set; }
        public string ob_dd_prompt_for_settling_emp { get; set; }
        public string ob_print_driver_rcpt_on_xfer { get; set; }
        public string ob_no_fpm_crs_slct_after_cmplt { get; set; }
        public string ob_use_condiment_placeholders { get; set; }
        public string ob_truncate_ttl { get; set; }
        public string ob_truncate_dsvc { get; set; }
        public int? incl_dsvc_seq { get; set; }
        public string ob_rvc_incl_svc_deflt_off { get; set; }
        public string ob_post_last_item_void_detail { get; set; }
        public string ob_keep_sides_after_uncombo { get; set; }
        public string ob_allow_0priced_mi_dsc_trggr { get; set; }
        public string ob_persist_prev_cashier { get; set; }
        public string ob_dont_hide_seats_when_filter { get; set; }
        public string ob_display_total_by_seat { get; set; }
        public string ob_mixed_lvl_upchg_combo_prices { get; set; }
        public string ob_use_combo_savings_discount { get; set; }
        public string ob_single_tray_tendering { get; set; }
        public string ob_auto_discount_effectiveness { get; set; }
        public string ob_post_split_ttls_to_new_chk { get; set; }
        public string ob_remove_persistent_auto_dsc { get; set; }
    }
}
