using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class rvc_add_def
    {
        public int rvc_seq { get; set; }
        public int obj_num { get; set; }
        public string name { get; set; }
        public int? offline_cc_tmed_seq { get; set; }
        public int? info_scrn_seq { get; set; }
        public short num_chk_info_lines { get; set; }
        public short? chks_prntd_before_auth { get; set; }
        public int? auth_n_pay_cc_vchr_trlr { get; set; }
        public string ob_et11_disp_nlu_numbers { get; set; }
        public string ob_rvc002_no_prn_time_on_chk { get; set; }
        public string ob_rvc003_prn_reprint_on_chk { get; set; }
        public string ob_rvc004_dont_prn_chk_num { get; set; }
        public string ob_rvc008_validate_void_rtn { get; set; }
        public string ob_rvc023_prorate_pms_itmzrs { get; set; }
        public string ob_rvc027_dont_sort_disp { get; set; }
        public string ob_rvc028_dont_consol_disp { get; set; }
        public string ob_rvc029_valdt_tips_decl { get; set; }
        public string ob_rvc038_no_clear_errors { get; set; }
        public string ob_rvc039_only_non_sls_jnl { get; set; }
        public string ob_rvc040_only_excptn_to_jnl { get; set; }
        public string ob_rvc042_pms1_bup_avail { get; set; }
        public string ob_rvc043_pms2_bup_avail { get; set; }
        public string ob_rvc044_order_chit_partial { get; set; }
        public string ob_rvc045_cust_rcpt_partial { get; set; }
        public string ob_rvc047_no_slip_prn_eject { get; set; }
        public string ob_rvc048_unsuprvsd_chk_rcpt { get; set; }
        public string ob_rvc051_sort_nlu_cond { get; set; }
        public string ob_rvc054_confirm_kybd_chng { get; set; }
        public string ob_rvc055_prn_prv_bal_on_chk { get; set; }
        public string ob_rvc059_prn_vvv_on_chk { get; set; }
        public string ob_rvc060_prn_station_num { get; set; }
        public string ob_rvc061_tmed_prn_link_mask { get; set; }
        public string ob_rvc064_blank_cust_disp { get; set; }
        public string ob_rvc081_void_red_ordr_chit { get; set; }
        public string ob_rvc082_prn_clsd_chk_chit { get; set; }
        public string ob_rvc084_on_demand_rcpt { get; set; }
        public string ob_rvc085_prn_rnd_by_rnd_ttl { get; set; }
        public string ob_rvc094_cond_on_mi_line { get; set; }
        public string ob_rvc099_dopple_local_ordrs { get; set; }
        public string ob_rvc100_incl_summ_dopple { get; set; }
        public string ob_rvc101_prn_tm_on_svc_ttl { get; set; }
        public string ob_rvc110_prn_trans_emp { get; set; }
        public string ob_rvc111_prn_mi_unit_price { get; set; }
        public string ob_rvc114_prn_chk_clsd_date { get; set; }
        public string ob_rvc116_2nd_flr_limit_pct { get; set; }
        public string ob_rvc117_2nd_flr_limit_amt { get; set; }
        public string ob_rvc118_2nd_auth_prn_vchr { get; set; }
        public string ob_rvc119_no_lf_after_vchr { get; set; }
        public string ob_rvc120_prn_2_cc_vchr { get; set; }
        public string ob_rvc124_stay_down_nlus { get; set; }
        public string ob_rvc125_prompt_prn_split { get; set; }
        public string ob_rvc126_alwys_prn_splt_chk { get; set; }
        public string ob_rvc128_short_delay_disply { get; set; }
        public string ob_rvc129_prn_tare_weight { get; set; }
        public string ob_rvc133_dont_split_pms_cov { get; set; }
        public string ob_rvc134_prompt_chk_prntr { get; set; }
        public string ob_rvc139_no_void_ordr_dev { get; set; }
        public string ob_rvc140_mask_id_mgr_proc { get; set; }
        public string ob_rvc141_no_pymnt_line_chk { get; set; }
        public string ob_rvc143_allow_pms_w_no_ref { get; set; }
        public string ob_rvc146_omit_crs_on_chk { get; set; }
        public string ob_rvc147_prn_dsc_after_sbtl { get; set; }
        public string ob_rvc148_dont_disp_chk_info { get; set; }
        public string ob_rvc149_omit_blnk_chk_info { get; set; }
        public string ob_rvc150_ordr_chit_wide_emp { get; set; }
        public string ob_rvc151_cond_masking { get; set; }
        public string ob_rvc154_20_char_ref { get; set; }
        public string ob_rvc155_cc_vchr_prn_bkgd { get; set; }
        public string ob_rvc156_show_reprint_on_cc { get; set; }
        public string ob_rvc162_auth_below_flr_msg { get; set; }
        public string ob_rvc163_tbl_on_rmt_trlr { get; set; }
        public string ob_rvc164_prn_split_chk_trlr { get; set; }
        public string ob_rvc166_wide_ttl { get; set; }
        public string ob_ochk_slu_svc_alert { get; set; }
        public string ob_print_IA_voucher { get; set; }
        public string ob_suppress_amt_on_IA { get; set; }
        public string ob_no_cust_name_on_cc_vchr { get; set; }
        public string ob_ca_status_uws_only { get; set; }
        public string ob_disable_chg_tip { get; set; }
        public string ob_disable_ca_status { get; set; }
        public string ob_pms_send_sprd { get; set; }
        public string ob_show_tbl_on_ochk_slu { get; set; }
        public string ob_show_num_on_ochk_slu { get; set; }
        public string ob_show_empl_on_ochk_slu { get; set; }
        public string ob_show_time_on_ochk_slu { get; set; }
        public string ob_show_ttl_on_ochk_slu { get; set; }
        public string ob_prompt_signature_match { get; set; }
        public string ob_svc_chg_before_tax_ttls { get; set; }
        public string ob_tbl_obj_svc_alert { get; set; }
        public string ob_tbl_obj_show_blank_legend { get; set; }
        public string ob_no_chg_tip_est { get; set; }
        public string ob_sim_1_autoload { get; set; }
        public string ob_sim_2_autoload { get; set; }
        public string ob_do_not_sort_cond { get; set; }
        public string ob_no_prompt_during_keyed_ca { get; set; }
        public string ob_print_ttl_on_cc_vchr { get; set; }
        public string ob_no_autocombo_confirm { get; set; }
        public string ob_rsvd01 { get; set; }
        public string ob_rsvd02 { get; set; }
        public string ob_rsvd03 { get; set; }
        public string ob_rsvd04 { get; set; }
        public string ob_rsvd05 { get; set; }
        public string chk_info_prn_fmt { get; set; }
        public short? num_lines_pre_chk_pg_1 { get; set; }
        public short? num_lines_on_chk_pg_1 { get; set; }
        public short? num_lines_pre_chk_pg_others { get; set; }
        public short? num_lines_on_chk_pg_others { get; set; }
        public short? chk_page_min_lines { get; set; }
        public short? num_lines_pre_cc_vchr { get; set; }
        public short? num_lines_pre_ordr_hdr { get; set; }
        public short? num_lines_pre_personal_chk { get; set; }
        public short? num_lines_per_rpt_prntr1 { get; set; }
        public short? num_lines_per_rpt_prntr2 { get; set; }
        public short? num_lines_per_prg_dump { get; set; }
        public int? sign_in_ts_scrn_seq { get; set; }
        public int? deflt_ts_scrn_seq { get; set; }
        public int? training_ts_scrn_seq { get; set; }
        public int? alpha_ts_scrn_seq { get; set; }
        public int? table_ts_scrn_seq { get; set; }
        public int? numeric_ts_scrn_seq { get; set; }
        public int? ochk_ts_style_seq { get; set; }
        public int? split_chk_ts_style_seq { get; set; }
        public int? edit_seats_ts_style_seq { get; set; }
        public int? edit_chk_share_ts_style_seq { get; set; }
        public int? edit_chk_cnt_ts_scrn_seq { get; set; }
        public int? edit_chk_numeric_ts_scrn_seq { get; set; }
        public int? mgr_func_ts_scrn_seq { get; set; }
        public string subttl_name { get; set; }
        public string pymnt_name { get; set; }
        public string ttl_due_name { get; set; }
        public string bev_name { get; set; }
        public string chk_endorse_line { get; set; }
        public int? cust_rcpt_hdr { get; set; }
        public int? cust_rcpt_trlr { get; set; }
        public int? chk_hdr { get; set; }
        public int? chk_trlr { get; set; }
        public string chk_data { get; set; }
        public int? local_order_hdr { get; set; }
        public int? cc_vchr_hdr { get; set; }
        public int? merch_cc_vchr_trlr { get; set; }
        public int? cust_cc_vchr_trlr { get; set; }
        public int? merch_init_auth_cc_vchr_trlr { get; set; }
        public int? cust_init_auth_cc_vchr_trlr { get; set; }
        public int? merch_opt_2nd_cc_vchr_trlr { get; set; }
        public int? cust_opt_2nd_cc_vchr_trlr { get; set; }
        public int? training_hdr { get; set; }
        public int? rsvd_hdr_seq { get; set; }
        public short? autofire_delay { get; set; }
        public int? ochk_slu_alert1_time { get; set; }
        public int? ochk_slu_alert2_time { get; set; }
        public short ochk_slu_alert1_color { get; set; }
        public short ochk_slu_alert2_color { get; set; }
        public short? ochk_slu_hold_icon_id { get; set; }
        public int? tbl_obj_alert1_time { get; set; }
        public int? tbl_obj_alert2_time { get; set; }
        public short tbl_obj_alert1_color { get; set; }
        public short tbl_obj_alert2_color { get; set; }
        public short? tbl_obj_seated_icon_id { get; set; }
        public short tbl_obj_seated_color { get; set; }
        public short? tbl_obj_alert1_icon_id { get; set; }
        public short? tbl_obj_alert2_icon_id { get; set; }
        public string sim_1_filename { get; set; }
        public string sim_2_filename { get; set; }
        public int? last_updated_by { get; set; }
        public DateTime? last_updated_date { get; set; }
        public string combo_savings_name { get; set; }
        public string ob_combo_savings_in_red { get; set; }
        public int? auth_n_pay_customer_trlr { get; set; }
        public string ob_autocombo_with_combo_key { get; set; }
        public int? cond_grp_mask_01 { get; set; }
        public int? cond_grp_mask_02 { get; set; }
        public string ob_do_not_print_gst_cnt { get; set; }
        public int? hht_sign_in_ts_scrn_seq { get; set; }
        public int? hht_alpha_ts_scrn_seq { get; set; }
        public int? hht_deflt_ts_scrn_seq { get; set; }
        public int? hht_numeric_ts_scrn_seq { get; set; }
        public int? hht_table_ts_scrn_seq { get; set; }
        public int? hht_training_ts_scrn_seq { get; set; }
        public int? hht_ochk_ts_style_seq { get; set; }
        public string ob_tid_consolidate { get; set; }
        public int? persnl_chk_endorsement_trlr_seq { get; set; }
        public int? persnl_chk_entry_ts { get; set; }
        public int? hht_persnl_chk_entry_ts { get; set; }
        public int? trailer_before_subtotal_seq { get; set; }
        public int? cond_grp_mask_03 { get; set; }
        public int? cond_grp_mask_04 { get; set; }
        public int? cond_grp_mask_05 { get; set; }
        public int? cond_grp_mask_06 { get; set; }
        public int? cond_grp_mask_07 { get; set; }
        public int? cond_grp_mask_08 { get; set; }
        public string ob_print_separate_tax_lines { get; set; }
        public string ob_consol_combo { get; set; }
        public string gst_info_print_format { get; set; }
        public string delv_info_print_format { get; set; }
        public string delv_note_print_format { get; set; }
        public string delv_time_print_format { get; set; }
        public string ob_allow_prev_rnd_acr { get; set; }
        public string ob_print_combo_savings { get; set; }
        public int? future_order_check_empl_seq { get; set; }
        public string ob_always_prnt_blk_sttl_sumry { get; set; }
        public short? display_consol_mode { get; set; }
        public string ob_base_flr_limit_1 { get; set; }
        public string ob_base_flr_limit_2 { get; set; }
        public int? cust_alt_cc_vchr_trlr { get; set; }
        public int? merch_alt_cc_vchr_trlr { get; set; }
        public short? check_consol_mode { get; set; }
        public string ob_max_combo_meal_consol { get; set; }
        public string ob_sort_current_round { get; set; }
        public string ob_consolidate_current_round { get; set; }
        public string watermark_image { get; set; }
        public decimal? charged_tip_limit { get; set; }
        public string ob_avs_if_manual_entry { get; set; }
        public string ob_full_avs_if_manual_entry { get; set; }
        public string ob_avs_required { get; set; }
        public string ob_full_avs_required { get; set; }
        public string ob_full_avs_if_card_not_present { get; set; }
        public string ob_print_payment_double_wide { get; set; }
        public int? void_chk_trlr { get; set; }
        public string ob_sort_menu_item_on_check { get; set; }
        public string ob_sort_display_dining_course { get; set; }
        public int? cust_auth_n_pay_cc_vchr_trlr { get; set; }
        public int? merch_auth_n_pay_cc_vchr_trlr { get; set; }
        public string roll_up_combo_prices { get; set; }
        public string ob_show_mi_on_ochk_slu { get; set; }
        public string ob_display_default_cond { get; set; }
        public string ob_disp_prefix_on_cond_line { get; set; }
        public int? rod_info_lines_entry_ts { get; set; }
        public int? hht_rod_info_lines_entry_ts { get; set; }
        public string ob_suppress_guest_check_id { get; set; }
        public string promise_time_print_format { get; set; }
        public string ob_cobranded_cc_always_prmpt { get; set; }
        public string mx870_form1 { get; set; }
        public string mx870_form2 { get; set; }
        public string mx870_form3 { get; set; }
        public string mx870_form4 { get; set; }
        public string mx870_form5 { get; set; }
        public string mx870_form6 { get; set; }
        public string mx870_form7 { get; set; }
        public string mx870_form8 { get; set; }
        public string mx870_form9 { get; set; }
        public string ob_mx870_skip_form1 { get; set; }
        public string ob_mx870_skip_form2 { get; set; }
        public string ob_mx870_skip_form3 { get; set; }
        public string ob_mx870_skip_form4 { get; set; }
        public string ob_mx870_skip_form5 { get; set; }
        public string ob_mx870_skip_form6 { get; set; }
        public string ob_mx870_skip_form7 { get; set; }
        public string ob_mx870_skip_form8 { get; set; }
        public string ob_mx870_skip_form9 { get; set; }
        public string ob_print_prefix_on_cond_line { get; set; }
        public int? pm_waste_hdr { get; set; }
        public int? pm_waste_trlr { get; set; }
        public int? mx870_gift_card_inquire_number { get; set; }
        public int? mx870_gift_card_interface { get; set; }
        public int? zero_bal_cc_vchr_trlr { get; set; }
        public int? zero_bal_customer_trlr { get; set; }
        public string secondary_encryption_key { get; set; }
        public string dbt_scndry_encryption_key { get; set; }
        public string ob_enable_offline_auth { get; set; }
        public string ob_enable_offline_flr_lmt { get; set; }
        public decimal? ca_offline_flr_lmt { get; set; }
        public int? chk_xfer_rqst_expire_time { get; set; }
        public short? chk_xfer_rqst_expired_icon { get; set; }
        public short? chk_xfer_rqst_expired_out_icon { get; set; }
        public short? chk_xfer_rqst_pending_icon { get; set; }
        public short? chk_xfer_rqst_pending_in_icon { get; set; }
        public short? chk_xfer_rqst_pending_out_icon { get; set; }
        public short? chk_xfer_rqst_reject_icon { get; set; }
        public short? chk_xfer_rqst_reject_out_icon { get; set; }
        public short? rush_order_slu_icon { get; set; }
        public short? vip_order_slu_icon { get; set; }
        public short? check_printed_slu_icon { get; set; }
        public short? rush_order_tbl_icon { get; set; }
        public short? vip_order_tbl_icon { get; set; }
        public short? check_printed_tbl_icon { get; set; }
        public short num_checks_to_print { get; set; }
        public string ob_prn_multiple_gst_chks { get; set; }
        public string ob_prompt_prn_multi_gst_chks { get; set; }
        public string ob_display_mi_consol_fpm_course { get; set; }
        public int? kds_course_alert1_color { get; set; }
        public int? kds_course_alert2_color { get; set; }
        public short? kds_course_alert1_icon_id { get; set; }
        public short? kds_course_alert2_icon_id { get; set; }
        public short? kds_course_peak_alert1_icon_id { get; set; }
        public short? kds_course_peak_alert2_icon_id { get; set; }
        public string ob_tbl_obj_alert_seated_only { get; set; }
        public string ob_tbl_obj_next_crs_if_kds_done { get; set; }
        public string ob_tbl_obj_course_alert { get; set; }
        public string ob_EMSR_confirm_amt { get; set; }
        public string ob_init_auth_0_acct_verif { get; set; }
        public string ob_prorate_combo_items_prices { get; set; }
        public int? payment_ts_scrn_seq { get; set; }
        public int? hht_payment_ts_scrn_seq { get; set; }
        public short? bev_only_slu_icon { get; set; }
        public short? bev_only_tbl_icon { get; set; }
        public int? active_order_list_ts { get; set; }
        public int? dispatched_order_list_ts { get; set; }
        public int? hht_active_order_list_ts { get; set; }
        public int? hht_dispatched_order_list_ts { get; set; }
        public short? epay_slu_icon { get; set; }
        public short? epay_tbl_icon { get; set; }
        public short? early_dt_expo_allowed_icon { get; set; }
        public short? early_dt_expo_done_icon { get; set; }
        public short? early_dt_expo_missed_icon { get; set; }
        public int? async_chk_payment_ts { get; set; }
        public int? hht_async_chk_payment_ts { get; set; }
        public string ob_beverage_only_indicator { get; set; }
        public string ob_suppress_table_printing { get; set; }
        public short? ordered_mi_indicator_icon { get; set; }
        public string ordered_mi_indicator_placement { get; set; }
        public string ob_ordered_mi_indicator_stretch { get; set; }
        public short? current_mi_indicator_icon { get; set; }
        public string current_mi_indicator_placement { get; set; }
        public string ob_current_mi_indicator_stretch { get; set; }
        public string ob_show_ts_key_ordered_mi_cnt { get; set; }
        public string ob_show_ts_key_mi_price { get; set; }
        public string ob_show_ts_key_mi_price_ccy_sym { get; set; }
        public string ob_prorate_combo_by_food_cost { get; set; }
        public string ob_tax_print_indicator_w_item { get; set; }
        public string ob_OPI_mode { get; set; }
        public int? OPI_default_tender_seq { get; set; }
        public string ob_prorate_combo_w_condiments { get; set; }
        public string ob_OPI_pin_debit_mode { get; set; }
        public string ob_OPI_cashback_support { get; set; }
        public string ob_do_not_send_check_KDS { get; set; }
        public string ob_do_not_send_voucher_KDS { get; set; }
        public string ob_OPI_donations_support { get; set; }
        public int? OPI_donations_svc_seq { get; set; }
    }
}
