using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class shift_cshr_trk_ttl
    {
        public int store_id { get; set; }
        public int cshr_ttl_seq { get; set; }
        public int shift_seq { get; set; }
        public int trk_grp_seq { get; set; }
        public int trk_cnt_01 { get; set; }
        public decimal trk_ttl_01 { get; set; }
        public int trk_cnt_02 { get; set; }
        public decimal trk_ttl_02 { get; set; }
        public int trk_cnt_03 { get; set; }
        public decimal trk_ttl_03 { get; set; }
        public int trk_cnt_04 { get; set; }
        public decimal trk_ttl_04 { get; set; }
        public int trk_cnt_05 { get; set; }
        public decimal trk_ttl_05 { get; set; }
        public int trk_cnt_06 { get; set; }
        public decimal trk_ttl_06 { get; set; }
        public int trk_cnt_07 { get; set; }
        public decimal trk_ttl_07 { get; set; }
        public int trk_cnt_08 { get; set; }
        public decimal trk_ttl_08 { get; set; }
        public int trk_cnt_09 { get; set; }
        public decimal trk_ttl_09 { get; set; }
        public int trk_cnt_10 { get; set; }
        public decimal trk_ttl_10 { get; set; }
        public int trk_cnt_11 { get; set; }
        public decimal trk_ttl_11 { get; set; }
        public int trk_cnt_12 { get; set; }
        public decimal trk_ttl_12 { get; set; }
        public int trk_cnt_13 { get; set; }
        public decimal trk_ttl_13 { get; set; }
        public int trk_cnt_14 { get; set; }
        public decimal trk_ttl_14 { get; set; }
        public int trk_cnt_15 { get; set; }
        public decimal trk_ttl_15 { get; set; }
        public int trk_cnt_16 { get; set; }
        public decimal trk_ttl_16 { get; set; }
        public int trk_cnt_17 { get; set; }
        public decimal trk_ttl_17 { get; set; }
        public int trk_cnt_18 { get; set; }
        public decimal trk_ttl_18 { get; set; }
        public int trk_cnt_19 { get; set; }
        public decimal trk_ttl_19 { get; set; }
        public int trk_cnt_20 { get; set; }
        public decimal trk_ttl_20 { get; set; }
        public int trk_cnt_21 { get; set; }
        public decimal trk_ttl_21 { get; set; }
        public int trk_cnt_22 { get; set; }
        public decimal trk_ttl_22 { get; set; }
        public int trk_cnt_23 { get; set; }
        public decimal trk_ttl_23 { get; set; }
        public int trk_cnt_24 { get; set; }
        public decimal trk_ttl_24 { get; set; }
        public int trk_cnt_25 { get; set; }
        public decimal trk_ttl_25 { get; set; }
        public int trk_cnt_26 { get; set; }
        public decimal trk_ttl_26 { get; set; }
        public int trk_cnt_27 { get; set; }
        public decimal trk_ttl_27 { get; set; }
        public int trk_cnt_28 { get; set; }
        public decimal trk_ttl_28 { get; set; }
        public int trk_cnt_29 { get; set; }
        public decimal trk_ttl_29 { get; set; }
        public int trk_cnt_30 { get; set; }
        public decimal trk_ttl_30 { get; set; }
        public int trk_cnt_31 { get; set; }
        public decimal trk_ttl_31 { get; set; }
        public int trk_cnt_32 { get; set; }
        public decimal trk_ttl_32 { get; set; }
        public int trk_cnt_33 { get; set; }
        public decimal trk_ttl_33 { get; set; }
        public int trk_cnt_34 { get; set; }
        public decimal trk_ttl_34 { get; set; }
        public int trk_cnt_35 { get; set; }
        public decimal trk_ttl_35 { get; set; }
        public int trk_cnt_36 { get; set; }
        public decimal trk_ttl_36 { get; set; }
        public int trk_cnt_37 { get; set; }
        public decimal trk_ttl_37 { get; set; }
        public int trk_cnt_38 { get; set; }
        public decimal trk_ttl_38 { get; set; }
        public int trk_cnt_39 { get; set; }
        public decimal trk_ttl_39 { get; set; }
        public int trk_cnt_40 { get; set; }
        public decimal trk_ttl_40 { get; set; }
        public int trk_cnt_41 { get; set; }
        public decimal trk_ttl_41 { get; set; }
        public int trk_cnt_42 { get; set; }
        public decimal trk_ttl_42 { get; set; }
        public int trk_cnt_43 { get; set; }
        public decimal trk_ttl_43 { get; set; }
        public int trk_cnt_44 { get; set; }
        public decimal trk_ttl_44 { get; set; }
        public int trk_cnt_45 { get; set; }
        public decimal trk_ttl_45 { get; set; }
        public int trk_cnt_46 { get; set; }
        public decimal trk_ttl_46 { get; set; }
        public int trk_cnt_47 { get; set; }
        public decimal trk_ttl_47 { get; set; }
        public int trk_cnt_48 { get; set; }
        public decimal trk_ttl_48 { get; set; }
        public int trk_cnt_49 { get; set; }
        public decimal trk_ttl_49 { get; set; }
        public int trk_cnt_50 { get; set; }
        public decimal trk_ttl_50 { get; set; }
        public int trk_cnt_51 { get; set; }
        public decimal trk_ttl_51 { get; set; }
        public int trk_cnt_52 { get; set; }
        public decimal trk_ttl_52 { get; set; }
        public int trk_cnt_53 { get; set; }
        public decimal trk_ttl_53 { get; set; }
        public int trk_cnt_54 { get; set; }
        public decimal trk_ttl_54 { get; set; }
        public int trk_cnt_55 { get; set; }
        public decimal trk_ttl_55 { get; set; }
        public int trk_cnt_56 { get; set; }
        public decimal trk_ttl_56 { get; set; }
        public int trk_cnt_57 { get; set; }
        public decimal trk_ttl_57 { get; set; }
        public int trk_cnt_58 { get; set; }
        public decimal trk_ttl_58 { get; set; }
        public int trk_cnt_59 { get; set; }
        public decimal trk_ttl_59 { get; set; }
        public int trk_cnt_60 { get; set; }
        public decimal trk_ttl_60 { get; set; }
        public int trk_cnt_61 { get; set; }
        public decimal trk_ttl_61 { get; set; }
        public int trk_cnt_62 { get; set; }
        public decimal trk_ttl_62 { get; set; }
        public int trk_cnt_63 { get; set; }
        public decimal trk_ttl_63 { get; set; }
        public int trk_cnt_64 { get; set; }
        public decimal trk_ttl_64 { get; set; }
        public int em_ttl_repl_seq { get; set; }
    }
}
