using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class tmed_def
    {
        public int tmed_seq { get; set; }
        public int obj_num { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string ob_tmed01_open_drwr { get; set; }
        public string ob_tpay02_req_amt_entry { get; set; }
        public string ob_tpay03_assume_pd_in_full { get; set; }
        public string ob_tpay04_chk_endorse_req { get; set; }
        public string ob_tmed05_ref_req { get; set; }
        public string ob_tmed06_valdtn_req { get; set; }
        public string ob_tpay10_post_to_gross_rcpt { get; set; }
        public string ob_tpay11_post_to_chg_rcpts { get; set; }
        public string ob_tmed12_exempt_auto_svc { get; set; }
        public string ob_tpay17_halo_active { get; set; }
        public string ob_tstl17_chain_order { get; set; }
        public string ob_tpay18_halo_by_amt { get; set; }
        public string ob_tstl18_dont_fire_order { get; set; }
        public string ob_tpay19_emp_meal { get; set; }
        public string ob_tstl19_reprint_chk { get; set; }
        public string ob_tdec19_tips_paid { get; set; }
        public string ob_tmed20_prn_sls_itmzrs { get; set; }
        public string ob_tmed21_prn_summ_ttls { get; set; }
        public string ob_tmed22_prn_trlr { get; set; }
        public string ob_tmed23_prn_chk { get; set; }
        public string ob_tmed24_prn_vat_ttl { get; set; }
        public string ob_tpay25_req_expr_date_entr { get; set; }
        public string ob_tpay26_allow_recall { get; set; }
        public string ob_tmed27_allow_curr_cnv { get; set; }
        public string ob_tpay28_pms_post_0 { get; set; }
        public string ob_tpay29_prn_2_pms_ref { get; set; }
        public string ob_tpay30_19_digit_pms_ref { get; set; }
        public string ob_tpay31_enable_pms { get; set; }
        public string ob_tpay33_dont_net_pms_chng { get; set; }
        public string ob_tpay34_cc_post_to_pms { get; set; }
        public string ob_tmed35_prn_memo_chk { get; set; }
        public string ob_tstl36_prn_seat_chk { get; set; }
        public string ob_tmed37_incr_filter { get; set; }
        public string ob_tpay38_prn_fcr_chk { get; set; }
        public string ob_tpay39_post_fcr_credit { get; set; }
        public string ob_tpay38_prn_personal_chk { get; set; }
        public string ob_tpay41_req_ca { get; set; }
        public string ob_tpay42_prompt_ca_imm_pymt { get; set; }
        public string ob_tpay43_dont_save_pms_resp { get; set; }
        public string ob_tpay44_tax_exempt_coupon { get; set; }
        public string ob_tpay45_vrfy_cc_mod_10 { get; set; }
        public string ob_tpay46_dont_chk_expr_date { get; set; }
        public string ob_tpay47_prn_with_lookup { get; set; }
        public string ob_tpay48_no_valdt_expr_date { get; set; }
        public string ob_tpay49_tnd_must_excd_tip { get; set; }
        public string ob_tmed50_sort_mi_by_seat { get; set; }
        public string ob_tpay51_prompt_cc_issu_num { get; set; }
        public string ob_tpay52_prompt_cc_iss_date { get; set; }
        public string ob_tpay53_prompt_opt_trlr { get; set; }
        public string ob_tpay54_cc_final_amt_reqd { get; set; }
        public string ob_tstl38_prn_on_rcpt_prntr { get; set; }
        public string ob_tstl43_prn_shared_chk { get; set; }
        public string ob_tstl51_suspend_trans { get; set; }
        public string ob_item_shareable { get; set; }
        public string ob_tpay_no_trlr_multi_round { get; set; }
        public string ob_tpay_prn_thai_tax_ar_line { get; set; }
        public string ob_tpay_prn_thai_tax_invoice { get; set; }
        public string ob_tstl_send_order { get; set; }
        public string ob_allow_with_euro { get; set; }
        public string ob_mask_cc_number { get; set; }
        public string ob_debit_card { get; set; }
        public string ob_dd_svc_ttl_key { get; set; }
        public string ob_prompt_during_keyed_ca { get; set; }
        public string ob_prompt_for_cashback { get; set; }
        public string ob_override_sign_out { get; set; }
        public string ob_rsvd05 { get; set; }
        public string ob_pin_reqd { get; set; }
        public string ob_mask_cc_exp { get; set; }
        public string ob_rsvd08 { get; set; }
        public string ob_rsvd09 { get; set; }
        public short priv_lvl { get; set; }
        public int? tax_class_seq { get; set; }
        public int? pms { get; set; }
        public int? mlvl_class_seq { get; set; }
        public int? prn_def_class_seq { get; set; }
        public int? chg_tip_dsvc_seq { get; set; }
        public int? tmed_slu_seq { get; set; }
        public short? nlu_num { get; set; }
        public int? key_num { get; set; }
        public short? icon_id { get; set; }
        public decimal? halo { get; set; }
        public short? cat { get; set; }
        public decimal? ca_tip_pct { get; set; }
        public decimal? ca_diff_pct { get; set; }
        public decimal? ca_scndary_flr_limit { get; set; }
        public decimal? ca_init_auth_amt { get; set; }
        public DateTime? effective_from { get; set; }
        public DateTime? effective_to { get; set; }
        public int? ca_driver { get; set; }
        public int? edc_driver { get; set; }
        public short? autofire_mode { get; set; }
        public int? last_updated_by { get; set; }
        public DateTime? last_updated_date { get; set; }
        public string ob_selective_fire { get; set; }
        public string ob_keep_held_status { get; set; }
        public string ob_personal_check { get; set; }
        public string ob_prompt_for_ssn { get; set; }
        public string ob_print_endorsement_trailer { get; set; }
        public string ob_mask_cardholder_name { get; set; }
        public string ob_rnd_tender { get; set; }
        public string ob_rnd_zero_tens { get; set; }
        public string ob_rnd_tens_digit { get; set; }
        public short insignificant_digits { get; set; }
        public int? external_type { get; set; }
        public decimal? ca_base_flr_lmt_1 { get; set; }
        public decimal? ca_base_flr_lmt_2 { get; set; }
        public string ob_offline_base_flr_lmt_1 { get; set; }
        public string ob_offline_base_flr_lmt_2 { get; set; }
        public string ob_prnt_vchr_base_flr_lmt_1 { get; set; }
        public string ob_prnt_vchr_base_flr_lmt_2 { get; set; }
        public string ob_no_prompt_avs { get; set; }
        public string ob_manual_entry_req_cvv { get; set; }
        public string ob_require_cvv { get; set; }
        public string ob_dflt_force_tbl_entry_svc_ttl { get; set; }
        public string ob_track_for_tips { get; set; }
        public string ob_complete_courses { get; set; }
        public string pin_input_prompt { get; set; }
        public short pin_input_len { get; set; }
        public string ob_persist_pymnt { get; set; }
        public string ob_persist_auto_discounts { get; set; }
        public string ob_check_placeholders { get; set; }
        public string ob_allow_debit_refunds { get; set; }
        public string ob_prompt_for_promise_time { get; set; }
        public string ob_allow_partial_auth { get; set; }
        public string ob_cobranded_cc { get; set; }
        public string ob_open_drawer_before_prompt { get; set; }
        public string ob_beverage_matching_reqd { get; set; }
        public string ob_prn_multiple_gst_chks { get; set; }
        public string ob_prompt_prn_multi_gst_chks { get; set; }
        public string ob_truncate_tender { get; set; }
        public string ob_exempt_incl_svc { get; set; }
        public string srm_payment_type { get; set; }
        public string ob_print_duplicate_chk { get; set; }
        public string ob_timed_order_dflt_svc_ttl { get; set; }
        public string ob_svc_ttl_put_away_chk { get; set; }
        public string ob_eco_print_chk { get; set; }
        public string ob_activate_async_pay_mode { get; set; }
        public int? tmed_link1_seq { get; set; }
        public int? tmed_link2_seq { get; set; }
        public int? tmed_link3_seq { get; set; }
        public int? tmed_link4_seq { get; set; }
        public string ob_donot_mask_first_6 { get; set; }
        public string ob_activate_chk_fiscal_lock { get; set; }
        public string card_type { get; set; }
    }
}
