using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class tms_turn_time_status
    {
        public int turn_time_seq { get; set; }
        public short? historic_turn_time { get; set; }
        public short? historic_turn_time_cnt { get; set; }
        public short? course_01_impact { get; set; }
        public short? course_02_impact { get; set; }
        public short? course_03_impact { get; set; }
        public short? course_04_impact { get; set; }
        public short? course_05_impact { get; set; }
        public short? course_06_impact { get; set; }
        public short? course_07_impact { get; set; }
        public short? course_08_impact { get; set; }
        public short? course_09_impact { get; set; }
        public short? course_10_impact { get; set; }
        public short? course_11_impact { get; set; }
        public short? course_12_impact { get; set; }
        public short? course_13_impact { get; set; }
        public short? course_14_impact { get; set; }
        public short? course_15_impact { get; set; }
        public short? course_16_impact { get; set; }
        public short? course_17_impact { get; set; }
        public short? course_18_impact { get; set; }
        public short? course_19_impact { get; set; }
        public short? course_20_impact { get; set; }
        public short? course_21_impact { get; set; }
        public short? course_22_impact { get; set; }
        public short? course_23_impact { get; set; }
        public short? course_24_impact { get; set; }
        public short? course_25_impact { get; set; }
        public short? course_26_impact { get; set; }
        public short? course_27_impact { get; set; }
        public short? course_28_impact { get; set; }
        public short? course_29_impact { get; set; }
        public short? course_30_impact { get; set; }
        public short? course_31_impact { get; set; }
        public short? course_32_impact { get; set; }
        public short? course_33_impact { get; set; }
        public short? course_34_impact { get; set; }
        public short? course_35_impact { get; set; }
        public short? course_36_impact { get; set; }
        public short? course_37_impact { get; set; }
        public short? course_38_impact { get; set; }
        public short? course_39_impact { get; set; }
        public short? course_40_impact { get; set; }
        public short? course_41_impact { get; set; }
        public short? course_42_impact { get; set; }
        public short? course_43_impact { get; set; }
        public short? course_44_impact { get; set; }
        public short? course_45_impact { get; set; }
        public short? course_46_impact { get; set; }
        public short? course_47_impact { get; set; }
        public short? course_48_impact { get; set; }
        public short? course_49_impact { get; set; }
        public short? course_50_impact { get; set; }
        public short? course_51_impact { get; set; }
        public short? course_52_impact { get; set; }
        public short? course_53_impact { get; set; }
        public short? course_54_impact { get; set; }
        public short? course_55_impact { get; set; }
        public short? course_56_impact { get; set; }
        public short? course_57_impact { get; set; }
        public short? course_58_impact { get; set; }
        public short? course_59_impact { get; set; }
        public short? course_60_impact { get; set; }
        public short? course_61_impact { get; set; }
        public short? course_62_impact { get; set; }
        public short? course_63_impact { get; set; }
        public short? course_64_impact { get; set; }
        public short? course_01_propensity { get; set; }
        public short? course_02_propensity { get; set; }
        public short? course_03_propensity { get; set; }
        public short? course_04_propensity { get; set; }
        public short? course_05_propensity { get; set; }
        public short? course_06_propensity { get; set; }
        public short? course_07_propensity { get; set; }
        public short? course_08_propensity { get; set; }
        public short? course_09_propensity { get; set; }
        public short? course_10_propensity { get; set; }
        public short? course_11_propensity { get; set; }
        public short? course_12_propensity { get; set; }
        public short? course_13_propensity { get; set; }
        public short? course_14_propensity { get; set; }
        public short? course_15_propensity { get; set; }
        public short? course_16_propensity { get; set; }
        public short? course_17_propensity { get; set; }
        public short? course_18_propensity { get; set; }
        public short? course_19_propensity { get; set; }
        public short? course_20_propensity { get; set; }
        public short? course_21_propensity { get; set; }
        public short? course_22_propensity { get; set; }
        public short? course_23_propensity { get; set; }
        public short? course_24_propensity { get; set; }
        public short? course_25_propensity { get; set; }
        public short? course_26_propensity { get; set; }
        public short? course_27_propensity { get; set; }
        public short? course_28_propensity { get; set; }
        public short? course_29_propensity { get; set; }
        public short? course_30_propensity { get; set; }
        public short? course_31_propensity { get; set; }
        public short? course_32_propensity { get; set; }
        public short? course_33_propensity { get; set; }
        public short? course_34_propensity { get; set; }
        public short? course_35_propensity { get; set; }
        public short? course_36_propensity { get; set; }
        public short? course_37_propensity { get; set; }
        public short? course_38_propensity { get; set; }
        public short? course_39_propensity { get; set; }
        public short? course_40_propensity { get; set; }
        public short? course_41_propensity { get; set; }
        public short? course_42_propensity { get; set; }
        public short? course_43_propensity { get; set; }
        public short? course_44_propensity { get; set; }
        public short? course_45_propensity { get; set; }
        public short? course_46_propensity { get; set; }
        public short? course_47_propensity { get; set; }
        public short? course_48_propensity { get; set; }
        public short? course_49_propensity { get; set; }
        public short? course_50_propensity { get; set; }
        public short? course_51_propensity { get; set; }
        public short? course_52_propensity { get; set; }
        public short? course_53_propensity { get; set; }
        public short? course_54_propensity { get; set; }
        public short? course_55_propensity { get; set; }
        public short? course_56_propensity { get; set; }
        public short? course_57_propensity { get; set; }
        public short? course_58_propensity { get; set; }
        public short? course_59_propensity { get; set; }
        public short? course_60_propensity { get; set; }
        public short? course_61_propensity { get; set; }
        public short? course_62_propensity { get; set; }
        public short? course_63_propensity { get; set; }
        public short? course_64_propensity { get; set; }
    }
}
