using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Micros3700Models.Models
{
    public class uws_def
    {
        public int uws_seq { get; set; }
        public int obj_num { get; set; }
        public int? rvc_seq { get; set; }
        public int? color_scheme_seq { get; set; }
        public int? uws_dev_seq { get; set; }
        public int? order_type_seq { get; set; }
        public int? ts_scrn_seq { get; set; }
        public int? hlp_scrn_seq { get; set; }
        public int? lang_seq { get; set; }
        public int? client_key_seq { get; set; }
        public short? default_kybd_num { get; set; }
        public int? auto_signoff_duration { get; set; }
        public short? open_drwr_timeout { get; set; }
        public short? override_chk_start_num { get; set; }
        public short? override_chk_end_num { get; set; }
        public string ob_su01_assign_drwr_by_ws { get; set; }
        public string ob_su02_compulse_drwr_close { get; set; }
        public string ob_su03_no_kybd_beep { get; set; }
        public string ob_su04_no_error_beep { get; set; }
        public string ob_su05_assign_cshr_by_ws { get; set; }
        public string ob_su06_dont_clr_trans_scrn { get; set; }
        public string ob_su07_other_drawer_frgn { get; set; }
        public string ob_su08_lcl_isn_baud_rate { get; set; }
        public string ob_su09_enable_auto_sign_off { get; set; }
        public string ob_su11_print_40_col { get; set; }
        public string ob_su12_disp_svc_ttl_time { get; set; }
        public string ob_su14_buffer_mag_card { get; set; }
        public string ob_su15_allow_open_drwr { get; set; }
        public string ob_su_allow_multi_rvc { get; set; }
        public string ob_allow_keyed_id_entry { get; set; }
        public string ob_uws_mono { get; set; }
        public string ob_standalone_enabled { get; set; }
        public string ob_suppress_prnt_err_in_sar { get; set; }
        public string ob_fcr_attached { get; set; }
        public string ob_enable_ordr_dev_01 { get; set; }
        public string ob_enable_ordr_dev_02 { get; set; }
        public string ob_enable_ordr_dev_03 { get; set; }
        public string ob_enable_ordr_dev_04 { get; set; }
        public string ob_enable_ordr_dev_05 { get; set; }
        public string ob_enable_ordr_dev_06 { get; set; }
        public string ob_enable_ordr_dev_07 { get; set; }
        public string ob_enable_ordr_dev_08 { get; set; }
        public string ob_enable_ordr_dev_09 { get; set; }
        public string ob_enable_ordr_dev_10 { get; set; }
        public string ob_enable_ordr_dev_11 { get; set; }
        public string ob_enable_ordr_dev_12 { get; set; }
        public string ob_enable_ordr_dev_13 { get; set; }
        public string ob_enable_ordr_dev_14 { get; set; }
        public string ob_enable_ordr_dev_15 { get; set; }
        public string ob_enable_ordr_dev_16 { get; set; }
        public string ob_enable_ordr_dev_17 { get; set; }
        public string ob_enable_ordr_dev_18 { get; set; }
        public string ob_enable_ordr_dev_19 { get; set; }
        public string ob_enable_ordr_dev_20 { get; set; }
        public string ob_enable_ordr_dev_21 { get; set; }
        public string ob_enable_ordr_dev_22 { get; set; }
        public string ob_enable_ordr_dev_23 { get; set; }
        public string ob_enable_ordr_dev_24 { get; set; }
        public string ob_enable_ordr_dev_25 { get; set; }
        public string ob_enable_ordr_dev_26 { get; set; }
        public string ob_enable_ordr_dev_27 { get; set; }
        public string ob_enable_ordr_dev_28 { get; set; }
        public string ob_enable_ordr_dev_29 { get; set; }
        public string ob_enable_ordr_dev_30 { get; set; }
        public string ob_enable_ordr_dev_31 { get; set; }
        public string ob_enable_ordr_dev_32 { get; set; }
        public string ob_deflt_ts_open_chk_slu { get; set; }
        public string ob_drive_thru_terminal { get; set; }
        public string ob_rsvd04 { get; set; }
        public string ob_rsvd05 { get; set; }
        public string ob_begin_check_w_oper_id { get; set; }
        public string ob_rsvd07 { get; set; }
        public string ob_rsvd08 { get; set; }
        public short? num_color_bits { get; set; }
        public short num_drawers { get; set; }
        public int? cust_rcpt_prntr { get; set; }
        public int? chk_prntr { get; set; }
        public int? local_ordr_prntr { get; set; }
        public int? memo_chk_prntr { get; set; }
        public int? validation_prntr { get; set; }
        public int? chk_endorse_prntr { get; set; }
        public int? tm_card_prntr { get; set; }
        public int? tm_chit_prntr { get; set; }
        public int? jnl_prntr { get; set; }
        public int? sar_bu_prntr { get; set; }
        public int? sar_bu_jnl_prntr { get; set; }
        public int? backup_jnl_prntr { get; set; }
        public int? ca_vchr_prntr { get; set; }
        public int? rpt_prntr { get; set; }
        public int? gui_fcr_prntr { get; set; }
        public int? rpt_prntr_2 { get; set; }
        public int? lds_prntr { get; set; }
        public int? prg_dump_prntr { get; set; }
        public int? local_bu_prntr { get; set; }
        public string thai_tax_uws_rd_num_line { get; set; }
        public decimal? update_count { get; set; }
        public int? min_serial_num_1 { get; set; }
        public int? min_serial_num_2 { get; set; }
        public int? max_serial_num_1 { get; set; }
        public int? max_serial_num_2 { get; set; }
        public string su_status { get; set; }
        public int? last_updated_by { get; set; }
        public DateTime? last_updated_date { get; set; }
        public int? cond_grp_mask_01 { get; set; }
        public int? cond_grp_mask_02 { get; set; }
        public string ob_review_chk { get; set; }
        public int? hht_ts_scrn_seq { get; set; }
        public int? cond_grp_mask_03 { get; set; }
        public int? cond_grp_mask_04 { get; set; }
        public int? cond_grp_mask_05 { get; set; }
        public int? cond_grp_mask_06 { get; set; }
        public int? cond_grp_mask_07 { get; set; }
        public int? cond_grp_mask_08 { get; set; }
        public string ob_gss_auto_kybd { get; set; }
        public string ob_gss_delivery { get; set; }
        public string ob_gss_caller_id { get; set; }
        public string ob_gss_auto_hide_caller_id { get; set; }
        public string ob_enable_prntr_dest_sel { get; set; }
        public int? local_order_remote_order_seq { get; set; }
        public string ob_enable_order_routing_profile { get; set; }
        public string theme_name { get; set; }
        public int? check_inactivity_timeout { get; set; }
        public int? check_inactivity_dialog_timeout { get; set; }
        public string ob_is_kiosk { get; set; }
        public string ob_enable_ui_start_location { get; set; }
        public short? ui_start_x { get; set; }
        public short? ui_start_y { get; set; }
        public short? ui_width { get; set; }
        public short? ui_height { get; set; }
        public int? ui_display_mode { get; set; }
        public string ob_req_till_before_check_begin { get; set; }
        public string ob_touchscreen_beep { get; set; }
        public int? dd_future_order_scrn_seq { get; set; }
        public string ob_rod_print_requires_pos { get; set; }
        public string ob_api_chk_print_through_pos { get; set; }
        public string ob_tms_enabled { get; set; }
        public string ob_prntr_dest_only_w_undocked { get; set; }
        public short? orientation_type { get; set; }
        public string card_acc_term_id { get; set; }
        public string ob_enable_ordr_dev_alt_01 { get; set; }
        public string ob_enable_ordr_dev_alt_02 { get; set; }
        public string ob_enable_ordr_dev_alt_03 { get; set; }
        public string ob_enable_ordr_dev_alt_04 { get; set; }
        public string ob_enable_ordr_dev_alt_05 { get; set; }
        public string ob_enable_ordr_dev_alt_06 { get; set; }
        public string ob_enable_ordr_dev_alt_07 { get; set; }
        public string ob_enable_ordr_dev_alt_08 { get; set; }
        public string ob_enable_ordr_dev_alt_09 { get; set; }
        public string ob_enable_ordr_dev_alt_10 { get; set; }
        public string ob_enable_ordr_dev_alt_11 { get; set; }
        public string ob_enable_ordr_dev_alt_12 { get; set; }
        public string ob_enable_ordr_dev_alt_13 { get; set; }
        public string ob_enable_ordr_dev_alt_14 { get; set; }
        public string ob_enable_ordr_dev_alt_15 { get; set; }
        public string ob_enable_ordr_dev_alt_16 { get; set; }
        public string ob_enable_ordr_dev_alt_17 { get; set; }
        public string ob_enable_ordr_dev_alt_18 { get; set; }
        public string ob_enable_ordr_dev_alt_19 { get; set; }
        public string ob_enable_ordr_dev_alt_20 { get; set; }
        public string ob_enable_ordr_dev_alt_21 { get; set; }
        public string ob_enable_ordr_dev_alt_22 { get; set; }
        public string ob_enable_ordr_dev_alt_23 { get; set; }
        public string ob_enable_ordr_dev_alt_24 { get; set; }
        public string ob_enable_ordr_dev_alt_25 { get; set; }
        public string ob_enable_ordr_dev_alt_26 { get; set; }
        public string ob_enable_ordr_dev_alt_27 { get; set; }
        public string ob_enable_ordr_dev_alt_28 { get; set; }
        public string ob_enable_ordr_dev_alt_29 { get; set; }
        public string ob_enable_ordr_dev_alt_30 { get; set; }
        public string ob_enable_ordr_dev_alt_31 { get; set; }
        public string ob_enable_ordr_dev_alt_32 { get; set; }
        public string ob_is_expo_station { get; set; }
        public int? sign_in_scrn_seq { get; set; }
        public string ob_enable_ot_printer_override { get; set; }
        public int? ochk_slu_ts_style_seq { get; set; }
        public string ob_kiosk_selection_mode { get; set; }
        public int? audit_jnl_prntr { get; set; }
        public int? backup_audit_jnl_prntr { get; set; }
    }
}
